(()=>{
  const $=id=>document.getElementById(id);
  const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const setMessage=(id,text,ok=false)=>{const el=$(id);el.textContent=text;el.classList.toggle('success',ok)};
  const copy=async value=>{if(value&&value!=='--')await navigator.clipboard.writeText(value)};

  // 时间戳转换
  const normalizeTimestamp=value=>{const raw=String(value).trim();if(!/^-?\d{1,19}$/.test(raw))throw new Error('请输入有效的数字时间戳');const digits=raw.replace('-','').length;let number=Number(raw),unit='秒';if(digits>=19){number/=1e6;unit='纳秒'}else if(digits>=16){number/=1e3;unit='微秒'}else if(digits>=13){unit='毫秒'}else number*=1e3;if(!Number.isFinite(number))throw new Error('时间戳超出可转换范围');const date=new Date(number);if(Number.isNaN(date.getTime()))throw new Error('时间戳超出日期范围');return{date,unit}};
  const renderTimestamp=value=>{try{const{date,unit}=normalizeTimestamp(value);$('timestampUnit').textContent=unit;$('timestampLocal').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full',timeStyle:'medium'}).format(date);$('timestampUtc').textContent=date.toUTCString();$('timestampIso').textContent=date.toISOString();setMessage('timestampMessage','转换成功',true)}catch(error){['timestampUnit','timestampLocal','timestampUtc','timestampIso'].forEach(id=>$(id).textContent='--');setMessage('timestampMessage',error.message)}};
  const pad=n=>String(n).padStart(2,'0'),now=new Date();$('dateInput').value=`${now.getFullYear()}-${pad(now.getMonth()+1)}-${pad(now.getDate())}T${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;$('timestampInput').value=Math.floor(Date.now()/1000);renderTimestamp($('timestampInput').value);const tick=()=>{$('currentTimestamp').textContent=String(Math.floor(Date.now()/1000))};tick();setInterval(tick,1000);
  $('timestampForm').addEventListener('submit',event=>{event.preventDefault();renderTimestamp($('timestampInput').value)});$('dateForm').addEventListener('submit',event=>{event.preventDefault();const date=new Date($('dateInput').value);if(Number.isNaN(date.getTime())){$('dateTimestamp').textContent='请选择有效日期';return}const precision=new FormData(event.currentTarget).get('precision');$('dateTimestamp').textContent=String(precision==='milliseconds'?date.getTime():Math.floor(date.getTime()/1000))});

  // Base64（支持 Unicode）
  const encodeUnicode=text=>{const bytes=new TextEncoder().encode(text);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary)};
  const decodeUnicode=text=>{const binary=atob(text.replace(/\s/g,'')),bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return new TextDecoder('utf-8',{fatal:true}).decode(bytes)};
  const runBase64=mode=>{try{const input=$('base64Input').value;if(!input)throw new Error('请先输入需要处理的内容');$('base64Output').value=mode==='encode'?encodeUnicode(input):decodeUnicode(input);setMessage('base64Message',mode==='encode'?'编码完成':'解码完成',true)}catch(error){$('base64Output').value='';setMessage('base64Message',mode==='decode'?'Base64 内容格式无效或不是 UTF-8 文本':error.message)}};
  $('base64Encode').addEventListener('click',()=>runBase64('encode'));$('base64Decode').addEventListener('click',()=>runBase64('decode'));$('base64Swap').addEventListener('click',()=>{const input=$('base64Input').value;$('base64Input').value=$('base64Output').value;$('base64Output').value=input;setMessage('base64Message','已交换输入与结果',true)});$('base64Clear').addEventListener('click',()=>{$('base64Input').value='';$('base64Output').value='';setMessage('base64Message','')});

  // JSON 格式化、校验与高亮
  const jsonHighlight=text=>{const token=/("(?:\\u[a-fA-F0-9]{4}|\\[^u]|[^\\"])*"\s*:)|("(?:\\u[a-fA-F0-9]{4}|\\[^u]|[^\\"])*")|\b(true|false|null)\b|-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b/g;let html='',cursor=0,match;while((match=token.exec(text))){html+=esc(text.slice(cursor,match.index));const type=match[1]?'key':match[2]?'string':match[3]?'literal':'number';html+=`<span class="json-${type}">${esc(match[0])}</span>`;cursor=match.index+match[0].length}return html+esc(text.slice(cursor))};
  const parseJson=()=>{const input=$('jsonInput').value.trim();if(!input)throw new Error('请先输入 JSON 内容');return JSON.parse(input)};
  const renderJson=(space,message)=>{try{const output=JSON.stringify(parseJson(),null,space);$('jsonOutput').innerHTML=jsonHighlight(output);setMessage('jsonMessage',message,true)}catch(error){$('jsonOutput').textContent='无法生成结果';setMessage('jsonMessage',`JSON 语法错误：${error.message}`)}};
  $('jsonFormat').addEventListener('click',()=>renderJson(2,'JSON 格式正确，已完成格式化'));$('jsonMinify').addEventListener('click',()=>renderJson(0,'JSON 格式正确，已完成压缩'));$('jsonValidate').addEventListener('click',()=>{try{parseJson();setMessage('jsonMessage','JSON 语法校验通过',true)}catch(error){setMessage('jsonMessage',`JSON 语法错误：${error.message}`)}});$('jsonSample').addEventListener('click',()=>{$('jsonInput').value='{"status":"ok","data":{"user":"LingTest","roles":["tester","developer"],"enabled":true},"count":2}';renderJson(2,'已载入并格式化示例',true)});$('jsonClear').addEventListener('click',()=>{$('jsonInput').value='';$('jsonOutput').textContent='等待输入 JSON';setMessage('jsonMessage','')});

  // 逐行 Diff（LCS）
  const diffLines=(before,after)=>{const a=before.split('\n'),b=after.split('\n');if(a.length>400||b.length>400)throw new Error('为保证浏览器流畅，每侧最多支持 400 行');const matrix=Array.from({length:a.length+1},()=>new Uint16Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)matrix[i][j]=a[i]===b[j]?matrix[i+1][j+1]+1:Math.max(matrix[i+1][j],matrix[i][j+1]);const rows=[];let i=0,j=0,oldLine=1,newLine=1;while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){rows.push({type:'same',oldLine:oldLine++,newLine:newLine++,text:a[i]});i++;j++}else if(j<b.length&&(i===a.length||matrix[i][j+1]>=matrix[i+1][j])){rows.push({type:'add',oldLine:'',newLine:newLine++,text:b[j++]})}else{rows.push({type:'del',oldLine:oldLine++,newLine:'',text:a[i++]})}}return rows};
  const renderDiff=()=>{try{const before=$('diffBefore').value,after=$('diffAfter').value;if(!before&&!after)throw new Error('请先输入需要对比的两份文本');const rows=diffLines(before,after),added=rows.filter(row=>row.type==='add').length,removed=rows.filter(row=>row.type==='del').length,same=rows.length-added-removed;$('diffSummary').innerHTML=`<span class="added">+${added} 新增</span><span class="removed">-${removed} 删除</span><span>${same} 行未变化</span>`;$('diffOutput').innerHTML=rows.map(row=>`<div class="diff-row ${row.type}"><span>${row.oldLine}</span><span>${row.newLine}</span><b>${row.type==='add'?'+':row.type==='del'?'-':' '}</b><code>${esc(row.text)||'&nbsp;'}</code></div>`).join('');setMessage('diffMessage',added||removed?'已完成差异对比':'两份文本完全一致',true)}catch(error){setMessage('diffMessage',error.message)}};
  $('diffCompare').addEventListener('click',renderDiff);$('diffJsonFormat').addEventListener('click',()=>{try{$('diffBefore').value=JSON.stringify(JSON.parse($('diffBefore').value),null,2);$('diffAfter').value=JSON.stringify(JSON.parse($('diffAfter').value),null,2);renderDiff()}catch(error){setMessage('diffMessage',`JSON 格式化失败：${error.message}`)}});$('diffSwap').addEventListener('click',()=>{const before=$('diffBefore').value;$('diffBefore').value=$('diffAfter').value;$('diffAfter').value=before;renderDiff()});$('diffSample').addEventListener('click',()=>{$('diffBefore').value='{"status":"ok","count":2,"version":"1.0"}';$('diffAfter').value='{"status":"ok","count":3,"version":"1.1"}';try{$('diffBefore').value=JSON.stringify(JSON.parse($('diffBefore').value),null,2);$('diffAfter').value=JSON.stringify(JSON.parse($('diffAfter').value),null,2)}catch{}renderDiff()});$('diffClear').addEventListener('click',()=>{$('diffBefore').value='';$('diffAfter').value='';$('diffSummary').textContent='等待对比';$('diffOutput').innerHTML='<p>差异结果将在这里显示</p>';setMessage('diffMessage','')});

  // 正则表达式测试
  const regexFlags=()=>[...document.querySelectorAll('.regex-flags input:checked')].map(input=>input.value).join('');
  const runRegex=()=>{try{const pattern=$('regexPattern').value,text=$('regexText').value;if(!pattern)throw new Error('请输入正则表达式');const flags=regexFlags(),regex=new RegExp(pattern,flags),matches=[];if(flags.includes('g')){let match;while((match=regex.exec(text))&&matches.length<500){matches.push(match);if(match[0]==='')regex.lastIndex++}}else{const match=regex.exec(text);if(match)matches.push(match)}const highlight=document.createDocumentFragment();let cursor=0;matches.forEach(match=>{highlight.append(document.createTextNode(text.slice(cursor,match.index)));const mark=document.createElement('mark');mark.textContent=match[0]||'∅';highlight.append(mark);cursor=match.index+match[0].length});highlight.append(document.createTextNode(text.slice(cursor)));$('regexHighlight').replaceChildren(highlight);$('regexSummary').textContent=`找到 ${matches.length} 处匹配 · /${pattern}/${flags}`;$('regexMatches').innerHTML=matches.length?matches.map((match,index)=>`<li><b>#${index+1}</b><code>${esc(match[0]||'空匹配')}</code><small>索引 ${match.index}${match.length>1?` · 捕获组：${match.slice(1).map(item=>esc(item??'未匹配')).join(' | ')}`:''}</small></li>`).join(''):'<li>没有匹配内容</li>';setMessage('regexMessage',matches.length?'正则表达式有效，匹配完成':'正则表达式有效，但没有找到匹配',true)}catch(error){$('regexSummary').textContent='正则表达式无效';$('regexHighlight').textContent=$('regexText').value||'匹配内容将在这里高亮';$('regexMatches').innerHTML='<li>暂无结果</li>';setMessage('regexMessage',`正则错误：${error.message}`)}};
  $('regexRun').addEventListener('click',runRegex);$('regexPhone').addEventListener('click',()=>{$('regexPattern').value='1[3-9]\\d{9}';$('regexText').value='有效号码：13800138000，无效号码：12800138000';runRegex()});$('regexEmail').addEventListener('click',()=>{$('regexPattern').value='[\\w.%+-]+@[\\w.-]+\\.[A-Za-z]{2,}';$('regexText').value='联系邮箱：qa@lingtest.dev，错误示例：qa@localhost';runRegex()});$('regexClear').addEventListener('click',()=>{$('regexPattern').value='';$('regexText').value='';$('regexSummary').textContent='等待测试';$('regexHighlight').textContent='匹配内容将在这里高亮';$('regexMatches').innerHTML='<li>暂无结果</li>';setMessage('regexMessage','')});

  document.querySelectorAll('[data-copy-target]').forEach(button=>button.addEventListener('click',async()=>{const target=$(button.dataset.copyTarget);await copy('value'in target?target.value:target.textContent);const old=button.textContent;button.textContent='已复制';setTimeout(()=>button.textContent=old,1200)}));
})();
