const API_BASE="https://timelens.cc",TOKEN_KEY="lingtest:admin-token";
const $=selector=>document.querySelector(selector),loginPanel=$("#loginPanel"),adminPanel=$("#adminPanel"),leadList=$("#leadList"),loginMessage=$("#loginMessage");
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
let token=sessionStorage.getItem(TOKEN_KEY)||"";
const statusLabels={new:"待处理",contacted:"已联系",approved:"已通过",active:"已激活",rejected:"已拒绝"};
async function api(path,options={}){const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`,...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok||data.code!==0)throw new Error(data.message||`HTTP ${response.status}`);return data.data||data}
function showAdmin(){loginPanel.hidden=true;adminPanel.hidden=false;$("#logout").hidden=false}
function showLogin(message=""){loginPanel.hidden=false;adminPanel.hidden=true;$("#logout").hidden=true;loginMessage.textContent=message}
function render(leads){const counts=leads.reduce((out,lead)=>(out[lead.status]=(out[lead.status]||0)+1,out),{});$("#summary").innerHTML=Object.entries(statusLabels).map(([key,label])=>`<span>${label} ${counts[key]||0}</span>`).join("");leadList.innerHTML=leads.length?leads.map(lead=>`<article class="lead-card" data-id="${escapeHtml(lead.id)}"><header><div><span>${escapeHtml(lead.source||"pricing")} · ${escapeHtml(new Date(lead.createdAt).toLocaleString())}</span><h2>${escapeHtml(lead.name)} ${lead.company?`· ${escapeHtml(lead.company)}`:""}</h2><div class="meta"><b>${escapeHtml(lead.contact)}</b><span>${escapeHtml(lead.role||"角色未填")}</span><span>${escapeHtml(lead.teamSize||"规模未填")}</span><span>${escapeHtml(lead.budgetRange||"预算未填")}</span></div></div><i class="status">${escapeHtml(statusLabels[lead.status]||lead.status)}</i></header><div class="need">${escapeHtml(lead.needSummary)}</div><div class="lead-actions"><select data-status><option value="new" ${lead.status==="new"?"selected":""}>待处理</option><option value="contacted" ${lead.status==="contacted"?"selected":""}>已联系</option><option value="rejected" ${lead.status==="rejected"?"selected":""}>已拒绝</option></select><button data-save>保存状态</button><button class="approve" data-approve>通过并生成激活码</button>${lead.licenseStatus?`<span>授权：${escapeHtml(lead.licenseStatus)}</span>`:""}</div></article>`).join(""):"<div class='empty'>当前筛选条件下还没有申请</div>"}
async function load(){try{const status=$("#statusFilter").value;const data=await api(`/api/lingtest/admin/leads${status?`?status=${encodeURIComponent(status)}`:""}`);showAdmin();render(data.leads||[])}catch(error){if(/凭证|401/.test(error.message)){token="";sessionStorage.removeItem(TOKEN_KEY);showLogin(error.message)}else leadList.innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`}}
$("#loginForm").addEventListener("submit",event=>{event.preventDefault();token=$("#adminToken").value.trim();sessionStorage.setItem(TOKEN_KEY,token);load()});
$("#logout").addEventListener("click",()=>{token="";sessionStorage.removeItem(TOKEN_KEY);showLogin()});
$("#refresh").addEventListener("click",load);$("#statusFilter").addEventListener("change",load);
leadList.addEventListener("click",async event=>{const card=event.target.closest(".lead-card");if(!card)return;const id=card.dataset.id;try{if(event.target.matches("[data-save]")){await api(`/api/lingtest/admin/leads/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status:card.querySelector("[data-status]").value})});await load()}if(event.target.matches("[data-approve]")){event.target.disabled=true;const data=await api(`/api/lingtest/admin/leads/${encodeURIComponent(id)}/approve`,{method:"POST",body:JSON.stringify({durationDays:365})});$("#activationCode").textContent=data.activationCode;$("#codeDialog").showModal();await load()}}catch(error){alert(error.message)}finally{if(event.target)event.target.disabled=false}});
$("#closeCode").addEventListener("click",()=>$("#codeDialog").close());$("#copyCode").addEventListener("click",async()=>{await navigator.clipboard.writeText($("#activationCode").textContent);$("#copyCode").textContent="已复制"});
if(token)load();else showLogin();
