const API_BASE='https://timelens.cc';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getToken=()=>{try{return JSON.parse(localStorage.getItem('timelens.pc.token'))||''}catch{return''}};
const authHeaders=()=>{const token=getToken();return token?{Authorization:`Bearer ${token}`,'X-Auth-Token':token}:{}};
const arrayOf=(d,keys=[])=>{if(Array.isArray(d))return d;for(const x of [d?.data,d?.result,d,...[d,d?.data,d?.result].flatMap(o=>keys.map(k=>o?.[k]))])if(Array.isArray(x))return x;return[]};
const builtins={hangzhou:{id:'hangzhou',destination:'杭州',title:'西湖城市漫游周末线',notes:'把湖滨散步、宋韵街区和咖啡慢游串成一条节奏舒服的两天一夜路线。',coverImage:'https://timelens.cc/images/official-changping.jpg',days:'2 天 1 夜',budget:'¥1200 - ¥1800',tags:['城市漫步','亲子友好','拍照出片']},xiamen:{id:'xiamen',destination:'厦门',title:'海风疗愈三日轻旅行',notes:'把鼓浪屿、海岸线和夜晚海风都装进一趟轻盈旅行。',coverImage:'https://timelens.cc/images/official-city-night.jpg',days:'3 天 2 夜',budget:'¥1800 - ¥2600',tags:['海边散心','文艺巡游','情侣友好']},dali:{id:'dali',destination:'大理',title:'苍洱之间的慢节奏假期',notes:'从古城到洱海，把风景、轻徒步与发呆时间都纳入路线安排。',coverImage:'https://timelens.cc/images/official-family-coast.jpg',days:'4 天 3 夜',budget:'¥2600 - ¥3600',tags:['自然风景','慢旅行','氛围感']}};
function toast(msg){const n=$('#notice');n.textContent=msg;n.hidden=false;setTimeout(()=>n.hidden=true,2600)}
function setMeta(name,value,property=false){let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.appendChild(el)}el.content=value}
function render(trip,records=[]){const title=trip.title||'路线详情',summary=trip.notes||trip.summary||'一条值得收藏的旅行路线。',destination=trip.destination||'精选路线';document.title=`${title}｜${destination}旅行路线 · 时光透卡`;const cover=trip.coverImage||trip.cover_image||'https://timelens.cc/images/official-city-night.jpg';setMeta('description',summary);setMeta('og:title',document.title,true);setMeta('og:description',summary,true);setMeta('og:image',cover,true);const tags=trip.tags||['路线合集',trip.rhythmLabel||trip.rhythm_label||'自在出发'];$('#routeContent').innerHTML=`<section class="route-hero" style="--cover:url('${esc(cover)}')"><div><span class="route-kicker">来自时光透卡的旅程邀请</span><h1>${esc(title)}</h1><p>${esc(destination)} · ${esc(trip.startDate||trip.start_date||trip.days||'随时出发')}</p><div class="tags">${tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div></section><section class="route-summary"><span class="eyebrow">ROUTE STORY</span><h2>为什么值得出发</h2><p>${esc(summary)}</p><div class="route-summary-footer"><span class="route-budget">${esc(trip.budget||'预算灵活')}</span><div class="route-reactions" aria-label="路线互动数据"><span class="route-view" title="浏览量"><b aria-hidden="true">◉</b><strong id="routeViewCount">${Number(trip.viewCount||trip.view_count||0)}</strong><small>浏览</small></span><button type="button" id="routeLike" class="reaction-button${trip.liked?' active':''}" aria-pressed="${!!trip.liked}"><b aria-hidden="true">♡</b><strong id="routeLikeCount">${Number(trip.likeCount||trip.like_count||0)}</strong><small>点赞</small></button><button type="button" id="routeFavorite" class="reaction-button${trip.favorited?' active':''}" aria-pressed="${!!trip.favorited}"><b aria-hidden="true">☆</b><strong id="routeFavoriteCount">${Number(trip.favoriteCount||trip.favorite_count||0)}</strong><small>收藏</small></button></div></div></section><div class="route-section-head"><div><span class="eyebrow">DAY BY DAY</span><h2>逐日行程</h2></div><p>${records.length?`共 ${records.length} 条路线记录`:'这个合集暂时没有公开的逐日记录'}</p></div><section class="route-timeline">${records.map((r,i)=>`<article class="day-record"><time><b>DAY ${String(i+1).padStart(2,'0')}</b><br>${esc(r.recordDate||r.record_date||r.date||'')}</time><div><h2>${esc(r.location||r.title||'当日行程')}</h2><p>${esc(r.essay||r.notes||r.content||'暂无记录说明')}</p>${r.imageUrl||r.image_url?`<img src="${esc(r.imageUrl||r.image_url)}" alt="${esc(r.location||'路线记录')}">`:''}</div></article>`).join('')}</section>`;window.currentTrip={...trip,title,summary,destination,cover};bindReactions(trip.id)}
function applyReactionState(state={}){const trip=window.currentTrip;if(!trip)return;for(const key of ['viewCount','likeCount','favoriteCount','liked','favorited'])if(state[key]!==undefined)trip[key]=state[key];$('#routeViewCount').textContent=Number(trip.viewCount||0);$('#routeLikeCount').textContent=Number(trip.likeCount||0);$('#routeFavoriteCount').textContent=Number(trip.favoriteCount||0);const like=$('#routeLike'),favorite=$('#routeFavorite');like.classList.toggle('active',!!trip.liked);like.setAttribute('aria-pressed',String(!!trip.liked));favorite.classList.toggle('active',!!trip.favorited);favorite.setAttribute('aria-pressed',String(!!trip.favorited))}
async function reactionRequest(path,method='POST'){const response=await fetch(`${API_BASE}${path}`,{method,headers:{'Content-Type':'application/json',...authHeaders()}}),raw=await response.text();let payload={};try{payload=raw?JSON.parse(raw):{}}catch{}if(!response.ok||Number(payload.code||0)!==0)throw Error(payload.message||`操作失败 (${response.status})`);return payload.data||{}}
async function toggleReaction(kind){const trip=window.currentTrip,button=$(kind==='like'?'#routeLike':'#routeFavorite');if(!trip?.id||button.disabled)return;if(!getToken()){toast('登录后即可点赞和收藏，正在前往登录页');setTimeout(()=>location.href='/timelens?login=1',900);return}const active=kind==='like'?!!trip.liked:!!trip.favorited,path=kind==='like'?`/api/trips/${encodeURIComponent(trip.id)}/reactions/like`:`/api/trips/${encodeURIComponent(trip.id)}/like`;button.disabled=true;try{applyReactionState(await reactionRequest(path,active?'DELETE':'POST'));toast(kind==='like'?(active?'已取消点赞':'感谢你的点赞'):(active?'已取消收藏':'路线已收藏'))}catch(e){toast(e.message)}finally{button.disabled=false}}
function bindReactions(id){$('#routeLike').onclick=()=>toggleReaction('like');$('#routeFavorite').onclick=()=>toggleReaction('favorite');if(!id||builtins[id])return;const key=`timelens.route.view.${id}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');reactionRequest(`/api/trips/${encodeURIComponent(id)}/view`).then(applyReactionState).catch(()=>sessionStorage.removeItem(key))}
function renderRoute(trip,records=[]){render(trip,records);const imageUrl=trip.routeImageUrl||trip.route_image_url||trip.routePlanImageUrl||trip.route_plan_image_url;if(!imageUrl)return;const description=$('.route-summary>p');description?.insertAdjacentHTML('afterend',`<figure class="route-plan-image"><img src="${esc(imageUrl)}" alt="${esc(trip.title||'旅行路线')}路线规划图" loading="lazy"><figcaption>路线规划图 · 点击图片可查看原图</figcaption></figure>`);const image=$('.route-plan-image img');if(image)image.onclick=()=>window.open(imageUrl,'_blank','noopener,noreferrer')}
function routeNavCard(route,direction){if(!route)return`<div class="route-nav-empty"><span>${direction==='prev'?'← 上一篇':'下一篇 →'}</span><b>${direction==='prev'?'已经是第一条路线':'已经是最后一条路线'}</b></div>`;const image=route.coverImage||route.cover_image||route.image||'https://timelens.cc/images/official-city-night.jpg';return`<a class="route-nav-card ${direction}" href="/timelens-route?id=${encodeURIComponent(route.id)}" aria-label="${direction==='prev'?'上一篇':'下一篇'}：${esc(route.title||route.destination||'旅行路线')}"><img src="${esc(image)}" alt="" loading="lazy"><span><small>${direction==='prev'?'← 上一篇':'下一篇 →'} · ${esc(route.destination||route.city||'精选目的地')}</small><b>${esc(route.title||'旅行路线')}</b></span></a>`}
async function loadRouteNavigation(currentId){let cloud=[];try{const response=await fetch(`${API_BASE}/api/trips/public?pageSize=100`),payload=await response.json();if(response.ok&&payload.success!==false)cloud=arrayOf(payload,['list','trips','publicTrips','routeCollections','items'])}catch(e){console.info('公开路线导航加载失败：',e.message)}const source=builtins[currentId]?Object.values(builtins):cloud,seen=new Set(),routes=source.filter(r=>{const id=String(r.id||'');if(!id||seen.has(id))return false;seen.add(id);return true}),index=routes.findIndex(r=>String(r.id)===String(currentId));if(index<0)return;const nav=document.createElement('nav');nav.className='route-pagination';nav.setAttribute('aria-label','相邻旅行路线');nav.innerHTML=`<div class="route-pagination-title"><span class="eyebrow">KEEP EXPLORING</span><h2>继续看看下一站</h2></div><div class="route-pagination-grid">${routeNavCard(routes[index-1],'prev')}${routeNavCard(routes[index+1],'next')}</div>`;$('#routeContent').appendChild(nav);nav.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.src='https://timelens.cc/images/official-city-night.jpg';img.classList.add('image-fallback')},{once:true}));window.routeNeighbors={prev:routes[index-1],next:routes[index+1]}}
async function load(){const id=new URLSearchParams(location.search).get('id');if(!id){$('#routeContent').innerHTML='<div class="empty"><h2>缺少路线参数</h2><p>请从路线广场重新选择路线。</p></div>';return}if(builtins[id]){renderRoute(builtins[id]);await loadRouteNavigation(id);return}try{const r=await fetch(`${API_BASE}/api/trips/public/${encodeURIComponent(id)}`,{headers:authHeaders()});const d=await r.json();if(!r.ok||d.success===false||(d.code!==undefined&&Number(d.code)!==0))throw Error(d.message||d.error||`请求失败 (${r.status})`);const root=d.data||d.result||d;renderRoute(root.trip||root.routeCollection||root.route_collection||root,root.records||root.routeRecords||root.route_records||[]);await loadRouteNavigation(id)}catch(e){$('#routeContent').innerHTML=`<div class="empty"><h2>路线加载失败</h2><p>${esc(e.message)}</p><a class="primary" href="/timelens">返回路线广场</a></div>`}}
let shareInProgress=false,shareReturnNotified=false;
function finishShare(message){const button=$('#shareRoute');shareInProgress=false;button.disabled=false;button.textContent='分享路线';button.focus({preventScroll:true});toast(message)}
$('#shareRoute').onclick=async()=>{if(shareInProgress)return;const button=$('#shareRoute'),t=window.currentTrip||{},text=`${t.destination||'旅行'}路线推荐｜${t.title||'一条值得出发的路线'}\n${t.summary||'完整逐日行程已经整理好了'}\n${location.href}`,data={title:document.title,text:t.summary||'我发现了一条值得出发的旅行路线',url:location.href};shareInProgress=true;shareReturnNotified=false;button.disabled=true;button.textContent='正在分享…';try{if(navigator.share){await navigator.share(data);finishShare('分享完成，可以继续浏览其他路线')}else{await navigator.clipboard.writeText(text);finishShare('分享文案和路线链接已复制，可粘贴到微信')}}catch(e){finishShare(e.name==='AbortError'?'已取消分享，可以继续浏览路线':'分享未完成，已保留当前页面')}};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&shareInProgress&&!shareReturnNotified){shareReturnNotified=true;toast('已返回路线详情，分享后可以继续浏览')}});
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&window.routeNeighbors?.prev)location.href=`/timelens-route?id=${encodeURIComponent(window.routeNeighbors.prev.id)}`;if(e.key==='ArrowRight'&&window.routeNeighbors?.next)location.href=`/timelens-route?id=${encodeURIComponent(window.routeNeighbors.next.id)}`});
load();
