const API_BASE='https://timelens.cc',AI_API='/api/ai/travel_plan';
const $=s=>document.querySelector(s),content=$('#content');
const store={get(k,d){try{return JSON.parse(localStorage.getItem('timelens.pc.'+k))??d}catch{return d}},set(k,v){localStorage.setItem('timelens.pc.'+k,JSON.stringify(v))}};
const state={page:'explore',tab:'plan',trips:store.get('trips',[]),activeId:store.get('activeId',''),records:store.get('records',[]),checklist:store.get('checklist',[]),markers:store.get('markers',[]),token:store.get('token',''),publicTrips:[]};
const guides=[
 {id:'hangzhou',city:'杭州',title:'西湖城市漫游周末线',summary:'把湖滨散步、宋韵街区和咖啡慢游串成一条节奏舒服的两天一夜路线。',image:'https://timelens.cc/images/official-changping.jpg',days:'2 天 1 夜',budget:'¥1200 - ¥1800',tags:['城市漫步','亲子友好','拍照出片']},
 {id:'xiamen',city:'厦门',title:'海风疗愈三日轻旅行',summary:'把鼓浪屿、海岸线和夜晚海风都装进一趟轻盈旅行。',image:'https://timelens.cc/images/official-city-night.jpg',days:'3 天 2 夜',budget:'¥1800 - ¥2600',tags:['海边散心','文艺巡游','情侣友好']},
 {id:'dali',city:'大理',title:'苍洱之间的慢节奏假期',summary:'从古城到洱海，把风景、轻徒步与发呆时间都纳入路线安排。',image:'https://timelens.cc/images/official-family-coast.jpg',days:'4 天 3 夜',budget:'¥2600 - ¥3600',tags:['自然风景','慢旅行','氛围感']}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function active(){return state.trips.find(x=>String(x.id)===String(state.activeId))||state.trips[0]}
function persist(){store.set('trips',state.trips);store.set('activeId',state.activeId);store.set('records',state.records);store.set('checklist',state.checklist);store.set('markers',state.markers)}
function toast(msg){const n=$('#notice');n.textContent=msg;n.hidden=false;setTimeout(()=>n.hidden=true,2600)}
async function api(path,{method='GET',body}={}){const r=await fetch(API_BASE+path,{method,headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token,'X-Auth-Token':state.token}:{})},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.message||d.msg||d.error||`请求失败 (${r.status})`);return d}
function arrayOf(d,keys=[]){if(Array.isArray(d))return d;for(const x of [d?.data,d?.result,d,...[d,d?.data,d?.result].flatMap(o=>keys.map(k=>o?.[k]))])if(Array.isArray(x))return x;return[]}
function card(x){return `<article class="card" data-route="${esc(x.id)}"><div class="cover" style="background-image:url('${esc(x.image||x.coverImage||x.cover_image||guides[0].image)}')"><span>${esc(x.city||x.destination||'精选路线')}</span></div><div class="card-body"><h3>${esc(x.title)}</h3><p>${esc(x.summary||x.notes||'一条值得收藏的旅行路线')}</p><div class="tags">${(x.tags||[x.days||'路线合集',x.budget||'轻松出发']).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="stats"><span>${esc(x.days||x.startDate||'随时出发')}</span><span>♡ ${x.likeCount||0}　⌁ ${x.viewCount||0}</span></div></div></article>`}
async function renderExplore(){content.innerHTML=`<div class="hero"><div><span class="eyebrow">TRAVEL SLOWLY · REMEMBER DEEPLY</span><h1>把想去的地方，<br>变成真正出发的路线。</h1><p>从路线灵感、AI 规划到出发清单和旅行记录，把每一次出发整理得更从容。</p><button id="heroCreate">开始规划旅程 →</button></div></div><div class="section-head"><div><h2>本周路线灵感</h2><p>为你挑选轻松、好走，也值得记录的路线</p></div></div><div class="cards" id="routeCards">${guides.map(card).join('')}</div>`;$('#heroCreate').onclick=openTripModal;try{const d=await api('/api/trips/public');state.publicTrips=arrayOf(d,['trips','publicTrips','routeCollections','list','items']);if(state.publicTrips.length)$('#routeCards').innerHTML=state.publicTrips.map(card).join('')}catch(e){console.info('使用内置精选路线：',e.message)}}
function renderWorkspace(){const t=active();if(!t){content.innerHTML=`<div class="empty"><h2>从一个目的地开始</h2><p>创建计划后，可在这里生成 AI 路线、管理清单并记录旅程。</p><button class="primary" id="emptyCreate">创建第一个计划</button></div>`;$('#emptyCreate').onclick=openTripModal;return}const recs=state.records.filter(r=>String(r.tripId)===String(t.id)),done=state.checklist.filter(i=>i.done).length;content.innerHTML=`<div class="workspace-head"><div><span class="eyebrow">CURRENT JOURNEY</span><h1>${esc(t.title||t.destination+'之旅')}</h1><p>${esc(t.startDate)} — ${esc(t.endDate)} · ${esc(t.companionLabel||'自在出发')} · ${esc(t.rhythmLabel||'经典平衡')}</p></div><div class="metrics"><div><b>${recs.length}</b><small>旅行记录</small></div><div><b>${done}/${state.checklist.length}</b><small>清单进度</small></div><div><b>${state.markers.length}</b><small>足迹点位</small></div></div></div><div class="tabs"><button data-tab="plan">规划</button><button data-tab="checklist">出发清单</button><button data-tab="records">单日记录</button><button data-tab="collection">路线合集</button></div><div id="tabPanel"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);b.onclick=()=>{state.tab=b.dataset.tab;renderWorkspace()}});renderTab(t,recs)}
function renderTab(t,recs){const p=$('#tabPanel');if(state.tab==='plan'){p.innerHTML=`<div class="panel"><h2>AI 路线规划</h2><p>根据当前计划生成可编辑的多日路线初稿，继续使用原有旅行规划接口。</p><div class="field"><label>补充偏好</label><textarea id="aiPrompt" placeholder="例如：喜欢历史街区和本地美食，节奏不要太赶……">${esc(t.notes||'')}</textarea></div><div class="modal-actions"><button class="primary" id="generate">生成路线初稿</button></div><div id="aiResult"></div></div>`;$('#generate').onclick=()=>generatePlan(t)}else if(state.tab==='checklist'){p.innerHTML=`<div class="panel"><h2>出发清单 <button class="ghost" id="addCheck">＋ 添加</button></h2><div id="checks">${state.checklist.length?state.checklist.map(i=>`<label class="check-row ${i.done?'done':''}"><input type="checkbox" data-check="${esc(i.id)}" ${i.done?'checked':''}><span><b>${esc(i.name)}</b>　${esc(i.desc||'')}</span></label>`).join(''):'<p>清单还是空的，点击添加第一项。</p>'}</div></div>`;document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{state.checklist.find(i=>String(i.id)===x.dataset.check).done=x.checked;persist();renderWorkspace()});$('#addCheck').onclick=openCheckModal}else if(state.tab==='records'){p.innerHTML=`<div class="section-head"><div><h2>旅行记录</h2><p>把每一天的路线、照片和提醒沉淀下来</p></div><button class="primary" id="addRecord">＋ 新增记录</button></div><div class="record-grid">${recs.length?recs.map(r=>`<article class="record"><time>${esc(r.date)}</time><h3>${esc(r.location)}</h3><p>${esc(r.essay||r.notes||'旅途中的一天')}</p></article>`).join(''):'<div class="empty">还没有记录，旅行会从第一天开始变得具体。</div>'}</div>`;$('#addRecord').onclick=openRecordModal}else p.innerHTML=`<div class="panel"><h2>${esc(t.title||t.destination+'路线合集')}</h2><p>${esc(t.notes||'这趟旅行的多日路线总览。')}</p><div class="tags"><span>${esc(t.destination)}</span><span>${esc(t.budget||'预算待定')}</span><span>${recs.length} 天记录</span></div><button class="primary" id="publish">公开到路线广场</button></div>`;$('#publish')?.addEventListener('click',()=>syncTrip(t))}
async function generatePlan(t){const btn=$('#generate'),out=$('#aiResult');btn.disabled=true;btn.textContent='正在规划…';try{const prompt=`目的地：${t.destination}\n日期：${t.startDate} 至 ${t.endDate}\n预算：${t.budget||'未填写'}\n同行：${t.companionLabel||'未填写'}\n节奏：${t.rhythmLabel||'未填写'}\n偏好：${$('#aiPrompt').value}`;const r=await fetch(AI_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_input:prompt})});const d=await r.json();if(!r.ok)throw Error(d.error||'生成失败');const text=d.plan||d.content||d.result||d.output||JSON.stringify(d,null,2);out.innerHTML=`<div class="panel"><h2>路线初稿</h2><div style="white-space:pre-wrap">${esc(text)}</div></div>`}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent='重新生成'}}
function renderFootprints(){const cities=[...new Set(state.markers.map(x=>x.city||x.name).filter(Boolean))];content.innerHTML=`<div class="workspace-head"><div><span class="eyebrow">MY FOOTPRINTS</span><h1>走过的地方，都有光</h1><p>同步小程序中的路线点位，也可以在 PC 端补充城市足迹。</p></div><button class="primary" id="addMarker">＋ 添加足迹</button></div><div class="panel"><h2>城市足迹 · ${cities.length} 城</h2><div class="tags">${cities.length?cities.map(c=>`<span style="font-size:14px;padding:8px 14px">⌖ ${esc(c)}</span>`).join(''):'还没有点亮城市'}</div></div>`;$('#addMarker').onclick=openMarkerModal}
function renderProfile(){content.innerHTML=`<div class="panel"><h2>我的旅行</h2><p>${state.token?'已连接 Timelens 云端账户':'当前使用本地模式。登录后可与小程序同步计划、记录、清单和足迹。'}</p><div class="metrics" style="justify-content:flex-start;margin:30px 0"><div><b>${state.trips.length}</b><small>旅行计划</small></div><div><b>${state.records.length}</b><small>旅行记录</small></div><div><b>${state.markers.length}</b><small>足迹点位</small></div></div><button class="primary" id="tokenBtn">${state.token?'更新访问令牌':'连接已有账户'}</button></div>`;$('#tokenBtn').onclick=openLoginModal}
function navigate(page){state.page=page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const meta={explore:['路线广场','发现值得出发的路线灵感'],workspace:['计划工作台','规划、准备并记录一趟完整旅程'],footprints:['城市足迹','把走过的地方慢慢点亮'],profile:['我的旅行','管理你的计划与云端数据']}[page];$('#pageTitle').textContent=meta[0];$('#pageSub').textContent=meta[1];({explore:renderExplore,workspace:renderWorkspace,footprints:renderFootprints,profile:renderProfile}[page])();updateSide()}
function updateSide(){const t=active();$('#sideTrip').innerHTML=t?`<small>当前计划</small><b>${esc(t.title||t.destination+'之旅')}</b><p>${esc(t.startDate)} · ${esc(t.destination)}</p>`:'<small>当前计划</small><b>还没有旅行计划</b><p>创建后将在这里快速进入</p>'}
function showModal(html,onSubmit){const m=$('#modal'),f=$('#modalBody');f.innerHTML=html;f.onsubmit=e=>{e.preventDefault();onSubmit(new FormData(f),m)};m.showModal()}
function openTripModal(pref={}){showModal(`<h2>创建旅行计划</h2><div class="form-grid"><div class="field full"><label>目的地</label><input name="destination" required value="${esc(pref.city||'')}" placeholder="想去哪里？"></div><div class="field"><label>出发日期</label><input type="date" name="startDate" required></div><div class="field"><label>结束日期</label><input type="date" name="endDate" required></div><div class="field"><label>预算</label><input name="budget" placeholder="例如 ¥5000"></div><div class="field"><label>同行方式</label><select name="companionLabel"><option>家人同行</option><option>朋友结伴</option><option>情侣出游</option><option>独自旅行</option></select></div><div class="field full"><label>偏好与备注</label><textarea name="notes">${esc(pref.summary||'')}</textarea></div></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">创建并开始规划</button></div>`,async(fd,m)=>{const o=Object.fromEntries(fd),trip={...o,id:'trip-'+Date.now(),title:o.destination+'之旅',rhythmLabel:'经典平衡',visibility:'private',createdAt:Date.now()};state.trips.unshift(trip);state.activeId=trip.id;if(!state.checklist.length)state.checklist=['身份证/护照','手机与充电器','常用药品','舒适步行鞋'].map((name,i)=>({id:Date.now()+i,name,done:false}));persist();m.close();navigate('workspace');if(state.token)syncTrip(trip)})}
async function syncTrip(t){try{await api('/api/trips',{method:'POST',body:{...t,tripId:t.id,trip_id:t.id,start_date:t.startDate,end_date:t.endDate,visibility:'public'}});toast('已同步到路线广场')}catch(e){toast(e.message)}}
function openCheckModal(){showModal(`<h2>添加清单项</h2><div class="field"><label>物品或事项</label><input name="name" required autofocus></div><div class="field"><label>备注</label><input name="desc"></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">添加</button></div>`,(f,m)=>{state.checklist.push({id:Date.now(),...Object.fromEntries(f),done:false});persist();m.close();renderWorkspace()})}
function openRecordModal(){showModal(`<h2>新增单日记录</h2><div class="form-grid"><div class="field"><label>日期</label><input type="date" name="date" required></div><div class="field"><label>地点 / 路线标题</label><input name="location" required></div><div class="field full"><label>路线说明与提醒</label><textarea name="essay"></textarea></div></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">保存记录</button></div>`,(f,m)=>{state.records.unshift({id:'record-'+Date.now(),tripId:active().id,...Object.fromEntries(f),createdAt:Date.now()});persist();m.close();renderWorkspace()})}
function openMarkerModal(){showModal(`<h2>点亮一座城市</h2><div class="field"><label>城市</label><input name="city" required></div><div class="field"><label>地点备注</label><input name="name"></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">点亮</button></div>`,(f,m)=>{state.markers.unshift({id:'marker-'+Date.now(),...Object.fromEntries(f),punchTime:Date.now()});persist();m.close();renderFootprints()})}
function openLoginModal(){showModal(`<h2>连接 Timelens 账户</h2><p>PC 浏览器无法调用微信 <code>wx.login</code>。请填入现有后端签发的访问令牌，接口域名和鉴权头均保持不变。</p><div class="field"><label>Access Token</label><textarea name="token" required>${esc(state.token)}</textarea></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">保存并同步</button></div>`,async(f,m)=>{state.token=String(f.get('token')).trim();store.set('token',state.token);m.close();toast('账户连接已保存');navigate('profile')})}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>navigate(x.dataset.page));$('#newTrip').onclick=()=>openTripModal();$('#loginBtn').onclick=()=>navigate('profile');$('#searchBtn').onclick=()=>{const q=prompt('输入目的地');if(q){document.querySelectorAll('.card').forEach(c=>c.hidden=!c.textContent.includes(q))}};content.addEventListener('click',e=>{const c=e.target.closest('[data-route]');if(c){const g=guides.find(x=>x.id===c.dataset.route);if(g)openTripModal(g)}});navigate('explore');
