const API_BASE='https://timelens.cc';
const FALLBACK_ROUTE_IMAGE='/img/timelens-route-fallback.png';
const FALLBACK_ROUTE_IMAGE_ABSOLUTE='https://laitest.tech/img/timelens-route-fallback.png';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routeCover=(trip={})=>{const value=String(trip.coverImage||trip.cover_image||trip.image||'').trim();return value&&!['null','undefined'].includes(value.toLowerCase())?value:FALLBACK_ROUTE_IMAGE};
const getToken=()=>{try{return JSON.parse(localStorage.getItem('timelens.pc.token'))||''}catch{return''}};
const authHeaders=()=>{const token=getToken();return token?{Authorization:`Bearer ${token}`,'X-Auth-Token':token}:{}};
const arrayOf=(d,keys=[])=>{if(Array.isArray(d))return d;for(const x of [d?.data,d?.result,d,...[d,d?.data,d?.result].flatMap(o=>keys.map(k=>o?.[k]))])if(Array.isArray(x))return x;return[]};
function shortenText(value,max=58){const text=String(value||'').replace(/\s+/g,' ').trim();return text.length>max?text.slice(0,max)+'…':text}
function routeDayCount(trip={}){const start=trip.startDate||trip.start_date,end=trip.endDate||trip.end_date||start;if(!start)return trip.days||'';const a=new Date(start+'T00:00:00'),b=new Date(end+'T00:00:00');if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))return trip.days||'';const days=Math.round((b-a)/86400000)+1;return days>0?days+' 天':trip.days||''}
function routeRecordLines(records=[],limit=8){const rows=records.slice(0,limit).map((r,i)=>{const day=`Day ${i+1}`,title=r.location||r.title||'当日路线',desc=shortenText(r.essay||r.notes||r.content||'',42);return desc?`${day}：${title} - ${desc}`:`${day}：${title}`});const extra=Math.max(0,records.length-rows.length);if(extra)rows.push(`还有 ${extra} 天路线，打开时光智行查看完整合集。`);return rows}
function distributionText(type,trip=window.currentTrip||{},records=window.currentRouteRecords||[]){const destination=trip.destination||trip.city||'这座城市',title=trip.title||`${destination}旅行路线`,date=trip.startDate||trip.start_date||trip.days||'随时出发',days=routeDayCount(trip)||'多日路线',budget=trip.budget||'预算灵活',vibe=trip.rhythmLabel||trip.rhythm_label||(trip.tags||[])[0]||'轻松出发',summary=shortenText(trip.summary||trip.notes||'一条值得收藏和参考的旅行路线。',90),lines=routeRecordLines(records,type==='question'?4:8),tags=[destination,`${destination}${days}路线`,'旅行路线','旅行攻略',vibe].filter(Boolean).map(x=>'#'+String(x).replace(/\s+/g,''));if(type==='article')return [`# ${title}`,'',`目的地：${destination}`,`时间：${date}`,`天数：${days}`,`预算：${budget}`,`适合：${vibe}`,'','## 为什么值得参考',summary,'','## 每日路线',...(lines.length?lines.map(x=>'- '+x):['- 暂无公开单日记录，可先作为路线灵感收藏。']),'','## 出发前提醒','- 出发前二次确认天气、交通、营业时间和预约规则。','- 按自己的预算和同行人调整停留时间。','','打开时光智行小程序，可以查看路线大图、作者足迹，并创建自己的同款计划。'].join('\n');if(type==='question')return [`问：${destination}怎么玩比较顺？`,`答：可以参考「${title}」。这条路线适合${vibe}，时间是${date}，预算参考为${budget}。`,'','问：每天怎么安排？',...(lines.length?lines.map(x=>'答：'+x):['答：当前路线还没有公开单日记录，可以先看路线大图和足迹点位。']),'','问：适合直接照着走吗？','答：适合作为初稿参考，出发前建议再次确认天气、交通、景区开放和预约情况。','','更多路线细节可在时光智行小程序查看。'].join('\n');return [`${destination}路线参考：${title}`,'',`${date} · ${days} · ${vibe}`,`预算参考：${budget}`,'',summary,'','路线安排：',...(lines.length?lines.map(x=>'- '+x):['- 暂无公开单日记录，可先查看路线大图和足迹。']),'','适合先收藏，再按自己的时间和预算改成同款计划。','',tags.join(' ')].join('\n')}
function distributionHtml(){return `<section class="route-distribution" aria-labelledby="routeDistributionTitle"><div class="route-distribution-head"><div><span class="eyebrow">DISTRIBUTION</span><h2 id="routeDistributionTitle">分发素材</h2></div><p>复制到小红书、公众号或搜索问答里引流</p></div><div class="route-distribution-grid"><button type="button" data-copy-distribution="xiaohongshu"><b>小红书文案</b><small>标题、正文和标签</small></button><button type="button" data-copy-distribution="article"><b>公众号提纲</b><small>结构化长文草稿</small></button><button type="button" data-copy-distribution="question"><b>问答版路线</b><small>适合搜索问答</small></button></div></section>`}
async function copyText(value){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value);return}const textarea=document.createElement('textarea');textarea.value=value;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.left='-9999px';document.body.appendChild(textarea);textarea.select();document.execCommand('copy');textarea.remove()}
function bindDistributionActions(){document.querySelectorAll('[data-copy-distribution]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await copyText(distributionText(button.dataset.copyDistribution));toast('分发素材已复制，可以粘贴到外部平台')}catch(e){toast('复制失败，请手动选择页面内容')}finally{button.disabled=false}})}
const builtins={hangzhou:{id:'hangzhou',destination:'杭州',title:'西湖城市漫游周末线',notes:'把湖滨散步、宋韵街区和咖啡慢游串成一条节奏舒服的两天一夜路线。',coverImage:'https://timelens.cc/images/official-changping.jpg',days:'2 天 1 夜',budget:'¥1200 - ¥1800',tags:['城市漫步','亲子友好','拍照出片']},xiamen:{id:'xiamen',destination:'厦门',title:'海风疗愈三日轻旅行',notes:'把鼓浪屿、海岸线和夜晚海风都装进一趟轻盈旅行。',coverImage:'https://timelens.cc/images/official-city-night.jpg',days:'3 天 2 夜',budget:'¥1800 - ¥2600',tags:['海边散心','文艺巡游','情侣友好']},dali:{id:'dali',destination:'大理',title:'苍洱之间的慢节奏假期',notes:'从古城到洱海，把风景、轻徒步与发呆时间都纳入路线安排。',coverImage:'https://timelens.cc/images/official-family-coast.jpg',days:'4 天 3 夜',budget:'¥2600 - ¥3600',tags:['自然风景','慢旅行','氛围感']}};
function toast(msg){const n=$('#notice');n.textContent=msg;n.hidden=false;setTimeout(()=>n.hidden=true,2600)}
function setMeta(name,value,property=false){let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`);if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.appendChild(el)}el.content=value}
function render(trip,records=[]){const title=trip.title||'路线详情',summary=trip.notes||trip.summary||'一条值得收藏的旅行路线。',destination=trip.destination||'精选路线';document.title=`${title}｜${destination}旅行路线 · 时光智行`;const cover=routeCover(trip),shareCover=cover.startsWith('/')?FALLBACK_ROUTE_IMAGE_ABSOLUTE:cover;setMeta('description',summary);setMeta('og:title',document.title,true);setMeta('og:description',summary,true);setMeta('og:image',shareCover,true);const tags=trip.tags||['路线合集',trip.rhythmLabel||trip.rhythm_label||'自在出发'];$('#routeContent').innerHTML=`<section class="route-hero" style="--cover:url('${esc(cover)}'),url('${FALLBACK_ROUTE_IMAGE}')"><div><span class="route-kicker">来自时光智行的旅程邀请</span><h1>${esc(title)}</h1><p>${esc(destination)} · ${esc(trip.startDate||trip.start_date||trip.days||'随时出发')}</p><div class="tags">${tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div></section><section class="route-summary"><span class="eyebrow">ROUTE STORY</span><h2>为什么值得出发</h2><p>${esc(summary)}</p><div class="route-summary-footer"><span class="route-budget">${esc(trip.budget||'预算灵活')}</span><div class="route-reactions" aria-label="路线互动数据"><span class="route-view" title="浏览量"><b aria-hidden="true">◉</b><strong id="routeViewCount">${Number(trip.viewCount||trip.view_count||0)}</strong><small>浏览</small></span><button type="button" id="routeLike" class="reaction-button${trip.liked?' active':''}" aria-pressed="${!!trip.liked}"><b aria-hidden="true">♡</b><strong id="routeLikeCount">${Number(trip.likeCount||trip.like_count||0)}</strong><small>点赞</small></button><button type="button" id="routeFavorite" class="reaction-button${trip.favorited?' active':''}" aria-pressed="${!!trip.favorited}"><b aria-hidden="true">☆</b><strong id="routeFavoriteCount">${Number(trip.favoriteCount||trip.favorite_count||0)}</strong><small>收藏</small></button></div></div></section>${distributionHtml()}<div class="route-section-head"><div><span class="eyebrow">DAY BY DAY</span><h2>逐日行程</h2></div><p>${records.length?`共 ${records.length} 条路线记录`:'这个合集暂时没有公开的逐日记录'}</p></div><section class="route-timeline">${records.map((r,i)=>`<article class="day-record"><time><b>DAY ${String(i+1).padStart(2,'0')}</b><br>${esc(r.recordDate||r.record_date||r.date||'')}</time><div><h2>${esc(r.location||r.title||'当日行程')}</h2><p>${esc(r.essay||r.notes||r.content||'暂无记录说明')}</p>${r.imageUrl||r.image_url?`<img src="${esc(r.imageUrl||r.image_url)}" alt="${esc(r.location||'路线记录')}">`:''}</div></article>`).join('')}</section>`;window.currentTrip={...trip,title,summary,destination,cover};window.currentRouteRecords=records;bindReactions(trip.id);bindDistributionActions()}
function applyReactionState(state={}){const trip=window.currentTrip;if(!trip)return;for(const key of ['viewCount','likeCount','favoriteCount','liked','favorited'])if(state[key]!==undefined)trip[key]=state[key];$('#routeViewCount').textContent=Number(trip.viewCount||0);$('#routeLikeCount').textContent=Number(trip.likeCount||0);$('#routeFavoriteCount').textContent=Number(trip.favoriteCount||0);const like=$('#routeLike'),favorite=$('#routeFavorite');like.classList.toggle('active',!!trip.liked);like.setAttribute('aria-pressed',String(!!trip.liked));favorite.classList.toggle('active',!!trip.favorited);favorite.setAttribute('aria-pressed',String(!!trip.favorited))}
async function reactionRequest(path,method='POST',body){const response=await fetch(`${API_BASE}${path}`,{method,headers:{'Content-Type':'application/json',...authHeaders()},body:body?JSON.stringify(body):undefined}),raw=await response.text();let payload={};try{payload=raw?JSON.parse(raw):{}}catch{}if(!response.ok||Number(payload.code||0)!==0)throw Error(payload.message||`操作失败 (${response.status})`);return payload.data||{}}
async function toggleReaction(kind){const trip=window.currentTrip,button=$(kind==='like'?'#routeLike':'#routeFavorite');if(!trip?.id||button.disabled)return;if(!getToken()){toast('登录后即可点赞和收藏，正在前往登录页');setTimeout(()=>location.href='/timelens?login=1',900);return}const active=kind==='like'?!!trip.liked:!!trip.favorited,path=kind==='like'?`/api/trips/${encodeURIComponent(trip.id)}/reactions/like`:`/api/trips/${encodeURIComponent(trip.id)}/like`;button.disabled=true;try{applyReactionState(await reactionRequest(path,active?'DELETE':'POST'));toast(kind==='like'?(active?'已取消点赞':'感谢你的点赞'):(active?'已取消收藏':'路线已收藏'))}catch(e){toast(e.message)}finally{button.disabled=false}}
function bindReactions(id){$('#routeLike').onclick=()=>toggleReaction('like');$('#routeFavorite').onclick=()=>toggleReaction('favorite');if(!id||builtins[id])return;const key=`timelens.route.view.${id}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');reactionRequest(`/api/trips/${encodeURIComponent(id)}/view`).then(applyReactionState).catch(()=>sessionStorage.removeItem(key))}
function renderRoute(trip,records=[]){render(trip,records);const reactions=$('.route-reactions'),hero=$('.route-hero');if(reactions&&hero)hero.appendChild(reactions);mountComments(trip.id);const imageUrl=trip.routeImageUrl||trip.route_image_url||trip.routePlanImageUrl||trip.route_plan_image_url;if(!imageUrl)return;const description=$('.route-summary>p');description?.insertAdjacentHTML('afterend',`<figure class="route-plan-image"><img src="${esc(imageUrl)}" alt="${esc(trip.title||'旅行路线')}路线规划图" loading="lazy"><figcaption>路线规划图 · 点击图片可查看原图</figcaption></figure>`);const image=$('.route-plan-image img');if(image)image.onclick=()=>window.open(imageUrl,'_blank','noopener,noreferrer')}
const commentEmojis=['😀','😊','😍','👍','👏','🎉','❤️','🌟','📍','🚗','🏕️','🍜'];
let replyingTo=null;
function mountComments(id){const timeline=$('.route-timeline');if(!timeline||!id||builtins[id])return;timeline.insertAdjacentHTML('afterend',`<section class="route-comments" id="routeComments"><div class="route-comments-head"><div><span class="eyebrow">TRAVEL TALK</span><h2>聊聊这条路线 <small id="commentCount">0</small></h2></div><p>分享建议，也给路线作者一点反馈</p></div><form id="commentForm" class="comment-form"><div class="comment-replying" id="commentReplying" hidden><span></span><button type="button" aria-label="取消回复">取消</button></div><textarea name="content" maxlength="500" rows="3" placeholder="例如：这条路线适合带孩子吗？或者分享你的当地经验……" aria-label="评论内容"></textarea><div class="comment-emoji-bar" aria-label="常用表情">${commentEmojis.map(emoji=>`<button type="button" data-emoji="${emoji}" aria-label="插入表情 ${emoji}">${emoji}</button>`).join('')}</div><div class="comment-form-actions"><small>2–500 字，友善交流</small><button type="submit" class="primary">${getToken()?'发表评论':'登录后评论'}</button></div></form><div id="commentList" class="comment-list"><p class="comment-empty">正在加载评论…</p></div></section>`);$('#commentForm').onsubmit=submitComment;$('#commentReplying button').onclick=cancelReply;document.querySelectorAll('[data-emoji]').forEach(button=>button.onclick=()=>insertCommentEmoji(button.dataset.emoji));loadComments(id)}
function formatCommentTime(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return'';return date.toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function commentCard(row,isReply=false){return`<article class="comment-item${isReply?' comment-reply':''}" data-comment-id="${esc(row.id)}"><div class="comment-avatar">${esc((row.authorName||'旅').slice(0,1))}</div><div><header><b>${esc(row.authorName||'旅行者')}</b>${isReply&&row.replyToName?`<span>回复 ${esc(row.replyToName)}</span>`:''}<time>${esc(formatCommentTime(row.createdAt))}</time></header><p>${esc(row.content)}</p><div class="comment-tools"><button type="button" class="comment-reply-button" data-author="${esc(row.authorName||'旅行者')}">回复</button>${row.canDelete?'<button type="button" class="comment-delete">删除</button>':''}</div></div></article>`}
function renderComments(data={}){const rows=data.list||[],list=$('#commentList');if(!list)return;$('#commentCount').textContent=Number(data.total??rows.length);const roots=rows.filter(row=>!row.parentCommentId),replies=new Map();rows.filter(row=>row.parentCommentId).forEach(row=>{const group=replies.get(String(row.parentCommentId))||[];group.push(row);replies.set(String(row.parentCommentId),group)});list.innerHTML=rows.length?roots.map(row=>`<div class="comment-thread">${commentCard(row)}${(replies.get(String(row.id))||[]).map(reply=>commentCard(reply,true)).join('')}</div>`).join(''):'<p class="comment-empty">还没有评论，成为第一个分享建议的人。</p>';list.querySelectorAll('.comment-delete').forEach(button=>button.onclick=()=>deleteComment(button.closest('[data-comment-id]').dataset.commentId));list.querySelectorAll('.comment-reply-button').forEach(button=>button.onclick=()=>startReply(button.closest('[data-comment-id]').dataset.commentId,button.dataset.author))}
async function loadComments(id=window.currentTrip?.id){if(!id)return;try{const response=await fetch(`${API_BASE}/api/trips/${encodeURIComponent(id)}/comments`,{headers:authHeaders()}),payload=await response.json();if(!response.ok||Number(payload.code||0)!==0)throw Error(payload.message||'评论加载失败');renderComments(payload.data)}catch(e){const list=$('#commentList');if(list)list.innerHTML=`<p class="comment-empty">${esc(e.message)}</p>`}}
function insertCommentEmoji(emoji){const textarea=$('#commentForm textarea'),start=textarea.selectionStart??textarea.value.length,end=textarea.selectionEnd??start;textarea.setRangeText(emoji,start,end,'end');textarea.focus()}
function startReply(commentId,authorName){if(!getToken()){toast('登录后即可回复评论，正在前往登录页');setTimeout(()=>location.href='/timelens?login=1',900);return}replyingTo={commentId,authorName};const box=$('#commentReplying');box.hidden=false;box.querySelector('span').textContent=`正在回复 ${authorName}`;const textarea=$('#commentForm textarea');textarea.placeholder=`回复 ${authorName}…`;textarea.focus();$('#commentForm').scrollIntoView({behavior:'smooth',block:'center'})}
function cancelReply(){replyingTo=null;const box=$('#commentReplying');box.hidden=true;box.querySelector('span').textContent='';$('#commentForm textarea').placeholder='例如：这条路线适合带孩子吗？或者分享你的当地经验……'}
async function submitComment(event){event.preventDefault();if(!getToken()){toast('登录后即可参与评论，正在前往登录页');setTimeout(()=>location.href='/timelens?login=1',900);return}const form=event.currentTarget,content=String(new FormData(form).get('content')||'').trim(),button=form.querySelector('.primary');if(content.length<2){toast('请至少输入 2 个字');return}button.disabled=true;button.textContent=replyingTo?'正在回复…':'正在发表…';try{await reactionRequest(`/api/trips/${encodeURIComponent(window.currentTrip.id)}/comments`,'POST',{content,parentCommentId:replyingTo?.commentId||null});form.reset();toast(replyingTo?'回复成功，对方会收到消息':'评论发表成功');cancelReply();await loadComments()}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent='发表评论'}}
async function deleteComment(commentId){if(!confirm('确定删除这条评论吗？'))return;try{await reactionRequest(`/api/trips/${encodeURIComponent(window.currentTrip.id)}/comments/${encodeURIComponent(commentId)}`,'DELETE');toast('评论已删除');await loadComments()}catch(e){toast(e.message)}}
function routeNavCard(route,direction){if(!route)return`<div class="route-nav-empty"><span>${direction==='prev'?'← 上一篇':'下一篇 →'}</span><b>${direction==='prev'?'已经是第一条路线':'已经是最后一条路线'}</b></div>`;const image=routeCover(route);return`<a class="route-nav-card ${direction}" href="/travel/${encodeURIComponent(route.id)}" aria-label="${direction==='prev'?'上一篇':'下一篇'}：${esc(route.title||route.destination||'旅行路线')}"><img src="${esc(image)}" alt="" loading="lazy"><span><small>${direction==='prev'?'← 上一篇':'下一篇 →'} · ${esc(route.destination||route.city||'精选目的地')}</small><b>${esc(route.title||'旅行路线')}</b></span></a>`}
async function loadRouteNavigation(currentId){let cloud=[];try{const response=await fetch(`${API_BASE}/api/trips/public?pageSize=100`),payload=await response.json();if(response.ok&&payload.success!==false)cloud=arrayOf(payload,['list','trips','publicTrips','routeCollections','items'])}catch(e){console.info('公开路线导航加载失败：',e.message)}const source=builtins[currentId]?Object.values(builtins):cloud,seen=new Set(),routes=source.filter(r=>{const id=String(r.id||'');if(!id||seen.has(id))return false;seen.add(id);return true}),index=routes.findIndex(r=>String(r.id)===String(currentId));if(index<0)return;const nav=document.createElement('nav');nav.className='route-pagination';nav.setAttribute('aria-label','相邻旅行路线');nav.innerHTML=`<div class="route-pagination-title"><span class="eyebrow">KEEP EXPLORING</span><h2>继续看看下一站</h2></div><div class="route-pagination-grid">${routeNavCard(routes[index-1],'prev')}${routeNavCard(routes[index+1],'next')}</div>`;$('#routeContent').appendChild(nav);nav.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.src=FALLBACK_ROUTE_IMAGE;img.classList.add('image-fallback')},{once:true}));window.routeNeighbors={prev:routes[index-1],next:routes[index+1]}}
async function load(){const pathMatch=location.pathname.match(/^\/travel\/([^/]+)\/?$/),id=pathMatch?decodeURIComponent(pathMatch[1]):new URLSearchParams(location.search).get('id');if(!id){$('#routeContent').innerHTML='<div class="empty"><h2>缺少路线参数</h2><p>请从路线广场重新选择路线。</p></div>';return}if(builtins[id]){renderRoute(builtins[id]);await loadRouteNavigation(id);return}try{const r=await fetch(`${API_BASE}/api/trips/public/${encodeURIComponent(id)}`,{headers:authHeaders()});const d=await r.json();if(!r.ok||d.success===false||(d.code!==undefined&&Number(d.code)!==0))throw Error(d.message||d.error||`请求失败 (${r.status})`);const root=d.data||d.result||d;renderRoute(root.trip||root.routeCollection||root.route_collection||root,root.records||root.routeRecords||root.route_records||[]);await loadRouteNavigation(id)}catch(e){$('#routeContent').innerHTML=`<div class="empty"><h2>路线加载失败</h2><p>${esc(e.message)}</p><a class="primary" href="/timelens">返回路线广场</a></div>`}}
let shareInProgress=false,shareReturnNotified=false;
function finishShare(message){const button=$('#shareRoute');shareInProgress=false;button.disabled=false;button.textContent='分享路线';button.focus({preventScroll:true});toast(message)}
$('#shareRoute').onclick=async()=>{if(shareInProgress)return;const button=$('#shareRoute'),t=window.currentTrip||{},text=`${t.destination||'旅行'}路线推荐｜${t.title||'一条值得出发的路线'}\n${t.summary||'完整逐日行程已经整理好了'}\n${location.href}`,data={title:document.title,text:t.summary||'我发现了一条值得出发的旅行路线',url:location.href};shareInProgress=true;shareReturnNotified=false;button.disabled=true;button.textContent='正在分享…';try{if(navigator.share){await navigator.share(data);finishShare('分享完成，可以继续浏览其他路线')}else{await navigator.clipboard.writeText(text);finishShare('分享文案和路线链接已复制，可粘贴到微信')}}catch(e){finishShare(e.name==='AbortError'?'已取消分享，可以继续浏览路线':'分享未完成，已保留当前页面')}};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&shareInProgress&&!shareReturnNotified){shareReturnNotified=true;toast('已返回路线详情，分享后可以继续浏览')}});
document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&window.routeNeighbors?.prev)location.href=`/travel/${encodeURIComponent(window.routeNeighbors.prev.id)}`;if(e.key==='ArrowRight'&&window.routeNeighbors?.next)location.href=`/travel/${encodeURIComponent(window.routeNeighbors.next.id)}`});
load();
