const API_BASE='https://timelens.cc',AI_API='/api/ai/travel_plan';
const $=s=>document.querySelector(s),content=$('#content');
const store={get(k,d){try{return JSON.parse(localStorage.getItem('timelens.pc.'+k))??d}catch{return d}},set(k,v){localStorage.setItem('timelens.pc.'+k,JSON.stringify(v))}};
const state={page:'explore',tab:'plan',trips:store.get('trips',[]),activeId:store.get('activeId',''),records:store.get('records',[]),checklist:store.get('checklist',[]),markers:store.get('markers',[]),token:store.get('token',''),publicTrips:[],destinationFilter:null,footprintSummary:null};
const DEFAULT_CHECKLIST=[
  ['documents_devices','证件与设备','身份证','出行必带'],['documents_devices','证件与设备','手机','保持联络'],['documents_devices','证件与设备','充电器','原装更稳妥'],['documents_devices','证件与设备','充电宝','长途备用'],['documents_devices','证件与设备','钱包','证件与银行卡'],['documents_devices','证件与设备','相机','记录风景'],
  ['clothes','穿搭衣物','换洗衣物','至少 3 套'],['clothes','穿搭衣物','内衣','按天数准备'],['clothes','穿搭衣物','袜子','舒适透气'],['clothes','穿搭衣物','帽子','遮阳保暖'],['clothes','穿搭衣物','轻便鞋','适合步行'],
  ['care_wash','护理洗漱','牙刷牙膏','洗漱套装'],['care_wash','护理洗漱','防晒霜','户外防护'],['care_wash','护理洗漱','洗面奶','清洁护理'],['care_wash','护理洗漱','浴巾','轻薄速干'],
  ['food_supply','饮食补给','水杯','随时补水'],['food_supply','饮食补给','简餐零食','路上补给'],['food_supply','饮食补给','水果','旅途清爽'],
  ['medicine_emergency','药品与应急','驱蚊液','夏季高频'],['medicine_emergency','药品与应急','肠胃药','应对饮食变化'],['medicine_emergency','药品与应急','退烧药','基础应急'],['medicine_emergency','药品与应急','创口贴','小擦伤备用']
];
const guides=[
 {id:'hangzhou',city:'杭州',title:'西湖城市漫游周末线',summary:'把湖滨散步、宋韵街区和咖啡慢游串成一条节奏舒服的两天一夜路线。',image:'https://timelens.cc/images/official-changping.jpg',days:'2 天 1 夜',budget:'¥1200 - ¥1800',tags:['城市漫步','亲子友好','拍照出片']},
 {id:'xiamen',city:'厦门',title:'海风疗愈三日轻旅行',summary:'把鼓浪屿、海岸线和夜晚海风都装进一趟轻盈旅行。',image:'https://timelens.cc/images/official-city-night.jpg',days:'3 天 2 夜',budget:'¥1800 - ¥2600',tags:['海边散心','文艺巡游','情侣友好']},
 {id:'dali',city:'大理',title:'苍洱之间的慢节奏假期',summary:'从古城到洱海，把风景、轻徒步与发呆时间都纳入路线安排。',image:'https://timelens.cc/images/official-family-coast.jpg',days:'4 天 3 夜',budget:'¥2600 - ¥3600',tags:['自然风景','慢旅行','氛围感']}
];
let destinationTreeCache=null,destinationIndexCache=null;
const cityCoords={北京:[39.9042,116.4074],上海:[31.2304,121.4737],广州:[23.1291,113.2644],深圳:[22.5431,114.0579],杭州:[30.2741,120.1551],厦门:[24.4798,118.0894],大理:[25.6065,100.2676],成都:[30.5728,104.0668],重庆:[29.563,106.5516],西安:[34.3416,108.9398],南京:[32.0603,118.7969],苏州:[31.2989,120.5853],武汉:[30.5928,114.3055],长沙:[28.2282,112.9388],昆明:[25.0389,102.7183],青岛:[36.0671,120.3826],三亚:[18.2528,109.5119],拉萨:[29.652,91.1721],乌鲁木齐:[43.8256,87.6168],香港:[22.3193,114.1694],澳门:[22.1987,113.5439],台北:[25.033,121.5654],韩国:[36.5,127.8],日本:[36.2048,138.2529],菲律宾:[12.8797,121.774],越南:[14.0583,108.2772],老挝:[19.8563,102.4955],泰国:[15.87,100.9925],马来西亚:[4.2105,101.9758],新加坡:[1.3521,103.8198],印度尼西亚:[-0.7893,113.9213],尼泊尔:[28.3949,84.124],巴基斯坦:[30.3753,69.3451],土耳其:[38.9637,35.2433],约旦:[30.5852,36.2384],马尔代夫:[3.2028,73.2207],英国:[55.3781,-3.436],瑞士:[46.8182,8.2275],意大利:[41.8719,12.5674],希腊:[39.0742,21.8243],俄罗斯:[61.524,105.3188],美国:[37.0902,-95.7129],加拿大:[56.1304,-106.3468],埃及:[26.8206,30.8025],南非:[-30.5595,22.9375],坦桑尼亚:[-6.369,34.8888]};
let footprintMap;
let markerSyncAttempted=false,checklistLoadedTrip='',planLoadedTrip='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function active(){return state.trips.find(x=>String(x.id)===String(state.activeId))||state.trips[0]}
function persist(){store.set('trips',state.trips);store.set('activeId',state.activeId);store.set('records',state.records);store.set('checklist',state.checklist);store.set('markers',state.markers)}
function addLocalDefaultChecklist(tripId){const legacyMap={'身份证/护照':'身份证','手机与充电器':'手机','常用药品':'肠胃药','舒适步行鞋':'轻便鞋'},legacyDone=new Set(state.checklist.filter(i=>!i.tripId&&legacyMap[i.name]&&i.done).map(i=>legacyMap[i.name]));state.checklist=state.checklist.filter(i=>i.tripId||!legacyMap[i.name]);const existing=new Set(state.checklist.filter(i=>String(i.tripId||'')===String(tripId)).map(i=>`${i.categoryKey}|${i.name}`));DEFAULT_CHECKLIST.forEach(([categoryKey,categoryName,name,desc],index)=>{if(!existing.has(`${categoryKey}|${name}`))state.checklist.push({id:`default-${tripId}-${index+1}`,tripId,categoryKey,categoryName,name,desc,done:legacyDone.has(name),source:'default'})})}
function normalizeChecklistItem(i){return{...i,id:i.id,tripId:i.tripId||i.trip_id,name:i.name||i.itemName||i.item_name||'',desc:i.desc||i.itemDesc||i.item_desc||'',categoryKey:i.categoryKey||i.category_key||'custom',categoryName:i.categoryName||i.category_name||'其他',done:Boolean(i.done)}}
async function loadChecklist(tripId,{refresh=false}={}){if(!state.token||!tripId||String(tripId).startsWith('trip-'))return;if(!refresh&&checklistLoadedTrip===String(tripId))return;checklistLoadedTrip=String(tripId);try{const d=await api(`/api/trips/${encodeURIComponent(tripId)}/checklist`);state.checklist=arrayOf(d,['list','items']).map(normalizeChecklistItem);persist();if(state.page==='workspace')renderWorkspace()}catch(e){checklistLoadedTrip='';toast('出发清单同步失败：'+e.message)}}
async function updateChecklistItem(item,done){const previous=item.done;item.done=done;persist();renderWorkspace();if(!state.token||!item.tripId)return;try{const d=await api(`/api/trips/${encodeURIComponent(item.tripId)}/checklist/items/${encodeURIComponent(item.id)}`,{method:'PUT',body:{done}});Object.assign(item,normalizeChecklistItem(d.data||{}));persist();renderWorkspace()}catch(e){item.done=previous;persist();renderWorkspace();toast('清单更新失败：'+e.message)}}
function toast(msg){const n=$('#notice');n.textContent=String(msg||'操作失败，请稍后重试');n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,3600)}
async function api(path,{method='GET',body}={}){let r;try{r=await fetch(API_BASE+path,{method,headers:{'Content-Type':'application/json',...(state.token?{Authorization:'Bearer '+state.token,'X-Auth-Token':state.token}:{})},body:body?JSON.stringify(body):undefined})}catch(e){throw Error(navigator.onLine?'网络连接失败，请稍后重试':'当前网络不可用，请检查网络连接')}const raw=await r.text(),d=raw?(()=>{try{return JSON.parse(raw)}catch{return{}}})():{};if(!r.ok||d.success===false||(d.code!==undefined&&Number(d.code)!==0)){if(r.status===401&&state.token){state.token='';store.set('token','');markerSyncAttempted=false;throw Error('登录已过期，请重新登录')}const error=Error(d.message||d.msg||d.error||`请求失败 (${r.status})`);error.status=r.status;error.code=Number(d.code||r.status);throw error}return d}
function arrayOf(d,keys=[]){if(Array.isArray(d))return d;for(const x of [d?.data,d?.result,d,...[d,d?.data,d?.result].flatMap(o=>keys.map(k=>o?.[k]))])if(Array.isArray(x))return x;return[]}
function card(x){return `<article class="card" data-route="${esc(x.id)}" data-event="open_route"><div class="cover" style="background-image:url('${esc(x.image||x.coverImage||x.cover_image||guides[0].image)}')"><span>${esc(x.city||x.destination||'精选路线')}</span></div><div class="card-body"><h3>${esc(x.title)}</h3><p>${esc(x.summary||x.notes||'一条值得收藏的旅行路线')}</p><div class="tags">${(x.tags||[x.days||'路线合集',x.budget||'轻松出发']).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="stats"><span>${esc(x.days||x.startDate||'随时出发')}</span><span>♡ ${x.likeCount||0}　⌁ ${x.viewCount||0}</span></div></div></article>`}
async function renderExplore(){const filter=state.destinationFilter;content.innerHTML=`<div class="hero"><div><span class="eyebrow">TIMELENS · 时光透卡</span><h1>时光透卡，<br>把想去的地方变成真正出发的路线。</h1><p>从目的地路线搜索、AI 旅行规划到出发清单和城市足迹记录，时光透卡让每一次旅程更容易规划、回看与分享。</p><button id="heroCreate">开始规划旅程 →</button></div></div><div class="section-head"><div id="routeHeading"><h2>${filter?esc(filter.name)+'旅行路线':'时光透卡精选旅行路线'}</h2><p>${filter?'包含该目的地下所有地区的公开路线':'为你挑选轻松、好走，也值得记录的城市与多日路线'}</p></div><div class="route-filter-actions"><button class="ghost" id="destinationFilterBtn">⌖ ${filter?esc(filter.name):'按目的地筛选'}</button>${filter?'<button class="text-button" id="clearDestinationFilter">清除</button>':''}</div></div><div class="cards" id="routeCards">${filter?'<div class="empty">正在加载目的地路线…</div>':guides.map(card).join('')}</div>`;$('#heroCreate').onclick=openTripModal;$('#destinationFilterBtn').onclick=openRouteDestinationFilter;$('#clearDestinationFilter')?.addEventListener('click',()=>{state.destinationFilter=null;renderExplore()});try{const query=filter?`?destinationCode=${encodeURIComponent(filter.code)}`:'';const d=await api('/api/trips/public'+query);state.publicTrips=arrayOf(d,['trips','publicTrips','routeCollections','list','items']);if(state.publicTrips.length)$('#routeCards').innerHTML=state.publicTrips.map(card).join('');else if(filter)$('#routeCards').innerHTML=`<div class="empty"><h2>${esc(filter.name)}暂时没有公开路线</h2><p>可以先创建一条计划，旅行后分享给更多人。</p><button class="primary" id="emptyFilterCreate">创建计划</button></div>`;$('#emptyFilterCreate')?.addEventListener('click',()=>openTripModal({city:filter?.name||'',destinationCode:filter?.code||''}))}catch(e){console.info('使用内置精选路线：',e.message);const heading=$('#routeHeading');if(heading)heading.insertAdjacentHTML('beforeend',`<p class="inline-warning">云端路线暂时不可用，当前展示时光透卡内置精选路线。</p>`);if(filter)$('#routeCards').innerHTML='<div class="empty">目的地路线加载失败，请稍后重试。</div>'}}
async function searchPublicRoutes(keyword){const q=String(keyword||'').trim();if(!q)return;const cards=$('#routeCards'),heading=$('#routeHeading');cards.innerHTML='<div class="empty">正在搜索值得出发的路线…</div>';heading.innerHTML=`<h2>“${esc(q)}”的路线</h2><p>正在查询公开路线合集</p>`;try{const d=await api('/api/trips/public?keyword='+encodeURIComponent(q));const results=arrayOf(d,['trips','publicTrips','routeCollections','list','items']);state.publicTrips=results;if(results.length){cards.innerHTML=results.map(card).join('');heading.innerHTML=`<h2>“${esc(q)}”的路线</h2><p>找到 ${results.length} 条公开路线 · <button class="text-button" id="clearSearch">查看全部</button></p>`}else{cards.innerHTML=`<div class="empty"><h2>还没有找到“${esc(q)}”</h2><p>换一个城市、景点或路线关键词试试。</p><button class="primary" id="searchAgain">重新搜索</button></div>`;heading.innerHTML='<h2>搜索结果</h2><p>没有匹配的公开路线</p>'}$('#clearSearch')?.addEventListener('click',()=>renderExplore());$('#searchAgain')?.addEventListener('click',openSearchModal)}catch(e){const fallback=guides.filter(x=>`${x.city} ${x.title} ${x.summary} ${(x.tags||[]).join(' ')}`.includes(q));cards.innerHTML=fallback.length?fallback.map(card).join(''):`<div class="empty"><h2>搜索暂时不可用</h2><p>${esc(e.message)}</p></div>`;heading.innerHTML=`<h2>“${esc(q)}”的路线</h2><p>当前展示本地匹配结果</p>`}}
function openSearchModal(){showModal(`<h2>搜索目的地</h2><p>输入城市、景点或路线关键词，查找公开旅行路线。</p><div class="field"><label>目的地或关键词</label><input name="keyword" required autofocus placeholder="例如：新疆、杭州、西湖"></div><div class="modal-actions"><button type="button" id="searchCancel">取消</button><button class="primary">搜索路线</button></div>`,(f,m)=>{const q=String(f.get('keyword')||'').trim();if(!q)return;m.close();searchPublicRoutes(q)});$('#searchCancel').onclick=()=>$('#modal').close()}
function renderWorkspace(){const t=active();if(!t){content.innerHTML=`<div class="empty"><h2>从一个目的地开始</h2><p>创建计划后，可在这里生成 AI 路线、管理清单并记录旅程。</p><button class="primary" id="emptyCreate">创建第一个计划</button></div>`;$('#emptyCreate').onclick=openTripModal;return}if(!state.token&&String(t.id).startsWith('trip-')){addLocalDefaultChecklist(t.id);persist()}if(state.token&&checklistLoadedTrip!==String(t.id))loadChecklist(t.id);const recs=state.records.filter(r=>String(r.tripId)===String(t.id)),tripChecks=state.checklist.filter(i=>!i.tripId||String(i.tripId)===String(t.id)),done=tripChecks.filter(i=>i.done).length;content.innerHTML=`<div class="workspace-head"><div><span class="eyebrow">CURRENT JOURNEY</span><h1>${esc(t.title||t.destination+'之旅')}</h1><p>${esc(t.startDate)} — ${esc(t.endDate)} · ${esc(t.companionLabel||'自在出发')} · ${esc(t.rhythmLabel||'经典平衡')}</p></div><div class="metrics"><div><b>${recs.length}</b><small>旅行记录</small></div><div><b>${done}/${tripChecks.length}</b><small>清单进度</small></div><div><b>${state.markers.length}</b><small>足迹点位</small></div></div></div><div class="tabs"><button data-tab="plan">规划</button><button data-tab="checklist">出发清单</button><button data-tab="records">单日记录</button><button data-tab="collection">路线合集</button></div><div id="tabPanel"></div>`;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);b.onclick=()=>{state.tab=b.dataset.tab;renderWorkspace()}});renderTab(t,recs)}
function renderPlanRecord(record,saveState=''){
  const out=$('#aiResult');if(!out||!record)return;
  const planJson=TimeLensPlan.normalize(record.planJson||record.rawPlan);
  out.innerHTML=TimeLensPlan.render(planJson,record)+`<p class="plan-save-state ${saveState==='error'?'error':saveState?'success':''}">${esc(saveState||'')}</p>`;
}
async function loadSavedPlan(t){
  if(!state.token||!t||String(t.id).startsWith('trip-')||planLoadedTrip===String(t.id))return;
  planLoadedTrip=String(t.id);
  try{const d=await api(`/api/trips/${encodeURIComponent(t.id)}/ai-plans/latest`);if(d.data){t.aiPlan=d.data;persist();renderPlanRecord(t.aiPlan,'已从云端加载最新方案')}}catch(e){planLoadedTrip='';const out=$('#aiResult');if(out&&!t.aiPlan)out.innerHTML=`<div class="inline-error" role="alert">路线方案读取失败：${esc(e.message)}</div>`}
}
async function savePlanRecord(t,record){
  t.aiPlan=record;persist();
  if(!state.token)return{saved:false,message:'方案已保存在当前浏览器；登录后可同步到云端'};
  if(String(t.id).startsWith('trip-')){const synced=await syncTrip(t);if(!synced)throw Error('旅行计划尚未同步到云端')}
  const d=await api(`/api/trips/${encodeURIComponent(t.id)}/ai-plans`,{method:'POST',body:{prompt:record.prompt,rawPlan:record.rawPlan,planJson:record.planJson,provider:record.provider,model:record.model,elapsedMs:record.elapsedMs}});
  t.aiPlan={...record,...(d.data||{})};planLoadedTrip=String(t.id);persist();
  return{saved:true,message:'方案已保存到云端，可在下次登录后继续查看'};
}
function renderTab(t,recs){const p=$('#tabPanel');if(state.tab==='plan'){p.innerHTML=`<div class="panel"><h2>AI 路线规划</h2><p>根据当前计划生成可编辑的多日路线初稿，继续使用原有旅行规划接口。</p><div class="field"><label>补充偏好</label><textarea id="aiPrompt" placeholder="例如：喜欢历史街区和本地美食，节奏不要太赶……">${esc(t.notes||'')}</textarea></div><div class="modal-actions"><button class="primary" id="generate">生成路线初稿</button></div><div id="aiResult"></div></div>`;$('#generate').onclick=()=>generatePlan(t);if(t.aiPlan)renderPlanRecord(t.aiPlan,'已加载上次保存的方案');loadSavedPlan(t)}else if(state.tab==='checklist'){const items=state.checklist.filter(i=>!i.tripId||String(i.tripId)===String(t.id)),groups=[...new Map(items.map(i=>[i.categoryKey,{name:i.categoryName,items:items.filter(x=>x.categoryKey===i.categoryKey)}])).values()];p.innerHTML=`<div class="panel"><div class="section-head"><div><h2>出发清单</h2><p>${items.filter(i=>i.done).length}/${items.length} 项已完成，手机与 PC 实时同步</p></div><button class="ghost" id="addCheck">＋ 添加</button></div><div id="checks">${groups.length?groups.map(g=>`<section class="check-group"><h3>${esc(g.name)}</h3>${g.items.map(i=>`<label class="check-row ${i.done?'done':''}"><input type="checkbox" data-check="${esc(i.id)}" ${i.done?'checked':''}><span><b>${esc(i.name)}</b>${i.desc?`<small>${esc(i.desc)}</small>`:''}</span></label>`).join('')}</section>`).join(''):'<p>清单还是空的，点击添加第一项。</p>'}</div></div>`;document.querySelectorAll('[data-check]').forEach(x=>x.onchange=()=>{const item=state.checklist.find(i=>String(i.id)===x.dataset.check);if(item)updateChecklistItem(item,x.checked)});$('#addCheck').onclick=openCheckModal}else if(state.tab==='records'){p.innerHTML=`<div class="section-head"><div><h2>旅行记录</h2><p>把每一天的路线、照片和提醒沉淀下来</p></div><button class="primary" id="addRecord">＋ 新增记录</button></div><div class="record-grid">${recs.length?recs.map(r=>`<article class="record"><time>${esc(r.date)}</time><h3>${esc(r.location)}</h3><p>${esc(r.essay||r.notes||'旅途中的一天')}</p></article>`).join(''):'<div class="empty">还没有记录，旅行会从第一天开始变得具体。</div>'}</div>`;$('#addRecord').onclick=openRecordModal}else p.innerHTML=`<div class="panel"><h2>${esc(t.title||t.destination+'路线合集')}</h2><p>${esc(t.notes||'这趟旅行的多日路线总览。')}</p><div class="tags"><span>${esc(t.destination)}</span><span>${esc(t.budget||'预算待定')}</span><span>${recs.length} 天记录</span></div><button class="primary" id="publish">公开到路线广场</button></div>`;$('#publish')?.addEventListener('click',()=>syncTrip(t,{publish:true}))}
async function generatePlan(t){
  const btn=$('#generate'),out=$('#aiResult');btn.disabled=true;btn.textContent='正在规划…';
  try{
    const prompt=`目的地：${t.destination}\n日期：${t.startDate} 至 ${t.endDate}\n预算：${t.budget||'未填写'}\n同行：${t.companionLabel||'未填写'}\n节奏：${t.rhythmLabel||'未填写'}\n偏好：${$('#aiPrompt').value}`;
    const r=await fetch(AI_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_input:prompt})});
    const raw=await r.text(),d=raw?(()=>{try{return JSON.parse(raw)}catch{return{}}})():{};
    if(!r.ok||d.code&&Number(d.code)!==0)throw Error(d.message||d.msg||d.error||`路线生成失败 (${r.status})`);
    const value=d.travel_plan||d.plan||d.content||d.result||d.output;
    const text=typeof value==='string'?value:(value?JSON.stringify(value,null,2):'');
    if(!text)throw Error('AI 已返回结果，但没有找到路线方案内容');
    const record={prompt,rawPlan:text,planJson:TimeLensPlan.parse(text),provider:d.provider||d.runtime?.active_provider||'',model:d.model||'',elapsedMs:Number(d.elapsed_ms||0),createdAt:new Date().toISOString()};
    renderPlanRecord(record,'路线已生成，正在保存…');
    try{const saved=await savePlanRecord(t,record);renderPlanRecord(t.aiPlan||record,saved.message);toast(saved.message)}catch(saveError){renderPlanRecord(record,`方案展示成功，但云端保存失败：${saveError.message}`);toast('路线已生成，但保存失败，请稍后重试')}
  }catch(e){const message=e?.message||'路线生成失败，请稍后重试';out.innerHTML=`<div class="inline-error" role="alert">${esc(message)}</div>`;toast(message)}finally{btn.disabled=false;btn.textContent='重新生成'}
}
function markerCoords(m){const lat=Number(m.latitude||m.lat),lng=Number(m.longitude||m.lng||m.lon);if(lat&&lng)return[lat,lng];const city=String(m.city||m.name||'').replace(/[市区县]$/,'');return cityCoords[city]||null}
async function loadFootprintSummary(){if(!state.token)return;try{const d=await api('/api/markers/summary');state.footprintSummary=d.data||null;if(state.page==='footprints')renderFootprints()}catch(e){console.info('足迹聚合暂不可用：',e.message)}}
async function loadFootprintDestinationIndex(){if(destinationIndexCache)return;try{const d=await api('/api/destinations?scene=marker&format=list'),items=arrayOf(d);destinationIndexCache=new Map(items.map(x=>[x.code,x]));let changed=false;state.markers.forEach(m=>{const code=m.destinationCode||m.destination_code,item=destinationIndexCache.get(code);if(!item)return;if(!m.destinationName){m.destinationName=item.name;changed=true}if(!m.destinationFullName){m.destinationFullName=item.fullName||item.name;changed=true}if(!m.destinationScope){m.destinationScope=item.scope;changed=true}});if(changed)persist();if(state.page==='footprints')renderFootprints()}catch(e){console.info('目的地中文目录暂不可用：',e.message)}}
async function syncCloudMarkers(){if(markerSyncAttempted||!state.token)return;markerSyncAttempted=true;try{const d=await api('/api/markers');const cloud=arrayOf(d,['markers','punchedMarkers','punched_markers','list','items']);if(cloud.length){const byId=new Map(state.markers.map(m=>[String(m.id||m.markerId||m.marker_id),m]));cloud.forEach(m=>{const id=String(m.id||m.markerId||m.marker_id||`${m.latitude||m.lat}-${m.longitude||m.lng}-${m.name||m.city}`);byId.set(id,{...byId.get(id),...m,id,city:m.city||m.cityName||m.city_name||m.name,latitude:m.latitude||m.lat,longitude:m.longitude||m.lng||m.lon,punchTime:m.punchTime||m.punch_time||m.createdAt||m.created_at})});state.markers=[...byId.values()];persist();renderFootprints()}}catch(e){toast('云端足迹同步失败：'+e.message)}}
async function syncAccountData(){if(!state.token)return;const merge=(local,cloud)=>{const rows=new Map(local.map(x=>[String(x.id||x.tripId||x.trip_id),x]));cloud.forEach(x=>{const id=String(x.id||x.tripId||x.trip_id);rows.set(id,{...rows.get(id),...x,id,startDate:x.startDate||x.start_date,endDate:x.endDate||x.end_date,tripId:x.tripId||x.trip_id})});return[...rows.values()]};try{const [td,rd,md]=await Promise.all([api('/api/trips'),api('/api/records'),api('/api/markers')]);state.trips=merge(state.trips,arrayOf(td,['trips','list','items']));state.records=merge(state.records,arrayOf(rd,['records','list','items']));state.markers=merge(state.markers,arrayOf(md,['markers','punchedMarkers','punched_markers','list','items']));if(!state.activeId&&state.trips[0])state.activeId=state.trips[0].id;persist();markerSyncAttempted=true;checklistLoadedTrip='';const t=active();if(t)await loadChecklist(t.id,{refresh:true});toast('微信账户中的旅行数据与出发清单已同步')}catch(e){toast('登录成功，部分云端数据同步失败：'+e.message)}}
function notificationText(item){if(item.type==='trip_reply')return`${item.actorName||'一位旅行者'} 回复了你在「${item.tripTitle||'旅行路线'}」的评论`;if(item.type==='trip_comment')return`${item.actorName||'一位旅行者'} 评论了「${item.tripTitle||'你的路线'}」`;if(item.type==='trip_favorite')return`${item.actorName||'一位旅行者'} 收藏了「${item.tripTitle||'你的路线'}」`;return`${item.actorName||'一位旅行者'} 点赞了「${item.tripTitle||'你的路线'}」`}
async function refreshNotificationBadge(){const button=$('#notificationBtn'),badge=$('#notificationBadge');if(!state.token){button.hidden=true;badge.hidden=true;return}button.hidden=false;try{const data=await api('/api/notifications/unread-count'),count=Number(data.data?.unreadCount||0);badge.textContent=count>99?'99+':count;badge.hidden=count===0}catch(e){badge.hidden=true}}
async function openNotifications(){if(!state.token){openLoginModal();return}try{const response=await api('/api/notifications'),data=response.data||{},rows=data.list||[];showModal(`<div class="notification-modal"><div class="notification-modal-head"><div><span class="eyebrow">INBOX</span><h2>旅行消息</h2></div>${data.unreadCount?'<button type="button" id="readAllNotifications">全部已读</button>':''}</div><div class="notification-list">${rows.length?rows.map(item=>`<button type="button" class="notification-item${item.isRead?'':' unread'}" data-notification-id="${esc(item.id)}" data-trip-id="${esc(item.tripId||'')}"><span class="notification-icon">${item.type==='trip_reply'?'回':item.type==='trip_comment'?'评':item.type==='trip_favorite'?'藏':'赞'}</span><span><b>${esc(notificationText(item))}</b>${item.summary&&(item.type==='trip_comment'||item.type==='trip_reply')?`<small>“${esc(item.summary)}”</small>`:''}<time>${esc(new Date(item.createdAt).toLocaleString('zh-CN'))}</time></span></button>`).join(''):'<p class="notification-empty">还没有新消息。分享公开路线后，点赞、收藏和评论会出现在这里。</p>'}</div><div class="modal-actions"><button type="button" id="notificationClose">关闭</button></div></div>`,async()=>{});$('#notificationClose').onclick=()=>$('#modal').close();$('#readAllNotifications')?.addEventListener('click',async()=>{await api('/api/notifications/read-all',{method:'PUT'});$('#modal').close();refreshNotificationBadge();openNotifications()});document.querySelectorAll('.notification-item').forEach(button=>button.onclick=async()=>{await api(`/api/notifications/${encodeURIComponent(button.dataset.notificationId)}/read`,{method:'PUT'});location.href='/timelens-route?id='+encodeURIComponent(button.dataset.tripId)})}catch(e){toast('消息加载失败：'+e.message)}}
function initFootprintMap(){const el=$('#footprintMap');if(!el||!window.L)return;footprintMap?.remove();footprintMap=L.map(el,{zoomControl:true,scrollWheelZoom:true}).setView([35.5,104],4);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(footprintMap);const points=[];state.markers.forEach(m=>{const p=markerCoords(m);if(!p)return;points.push(p);const title=esc(m.city||m.name||'城市足迹'),note=esc(m.address||m.desc||m.note||'旅行中的一个足迹点'),date=m.punchTime?new Date(Number(m.punchTime)||m.punchTime).toLocaleDateString('zh-CN'):'';L.marker(p).addTo(footprintMap).bindPopup(`<b>${title}</b><br>${note}${date?`<br><small>${esc(date)}</small>`:''}`)});if(points.length)footprintMap.fitBounds(points,{padding:[45,45],maxZoom:11});setTimeout(()=>footprintMap?.invalidateSize(),0)}
function localFootprintDestinations(markers){const grouped=new Map;markers.forEach(m=>{const code=m.destinationCode||m.destination_code;if(!code)return;const current=grouped.get(code)||{code,name:m.destinationName||m.destination_name||code,fullName:m.destinationFullName||m.destination_full_name||m.destinationName||m.destination_name||code,scope:m.destinationScope||m.destination_scope||'domestic',pointCount:0};current.pointCount+=1;grouped.set(code,current)});return[...grouped.values()]}
function renderFootprints(){const cities=[...new Set(state.markers.map(x=>x.city||x.name).filter(Boolean))],summary=state.footprintSummary,destinations=summary?.destinations?.length?summary.destinations:localFootprintDestinations(state.markers);content.innerHTML=`<div class="workspace-head"><div><span class="eyebrow">MY FOOTPRINTS</span><h1>走过的地方，都有光</h1><p>同步小程序中的路线点位，也可以在 PC 端补充城市足迹。</p></div><button class="primary" id="addMarker">＋ 添加足迹</button></div><div class="footprint-metrics"><div><b>${summary?.destinationCount??destinations.length??cities.length}</b><small>去过的目的地</small></div><div><b>${summary?.domesticCount??destinations.filter(d=>d.scope==='domestic').length}</b><small>国内目的地</small></div><div><b>${summary?.internationalCount??destinations.filter(d=>d.scope==='international').length}</b><small>国外目的地</small></div><div><b>${state.markers.length}</b><small>足迹记录</small></div></div><div class="panel"><div class="section-head" style="margin-top:0"><div><h2>足迹地图</h2><p>${state.markers.length?`已点亮 ${summary?.destinationCount??destinations.length??cities.length} 个目的地 · ${state.markers.length} 个点位`:'添加足迹后，地图会自动定位并点亮城市'}</p></div></div><div id="footprintMap" style="height:460px;border-radius:14px;overflow:hidden;background:#e8f0ec"></div></div><div class="panel"><h2>目的地足迹</h2><div class="footprint-destinations">${destinations.length?destinations.map(d=>`<article><small>${esc(d.scope==='domestic'?'国内':'国外')}</small><b>${esc(d.name)}</b><span>${esc(d.fullName)} · ${d.pointCount} 个点位</span></article>`).join(''):(cities.length?cities.map(c=>`<article><small>待归类</small><b>${esc(c)}</b><span>历史足迹</span></article>`).join(''):'还没有点亮城市')}</div></div>`;$('#addMarker').onclick=openMarkerModal;initFootprintMap();syncCloudMarkers();if(state.token&&!state.footprintSummary)loadFootprintSummary();if(destinations.some(d=>String(d.name||'').startsWith('cn-')))loadFootprintDestinationIndex()}
function renderProfile(){content.innerHTML=`<div class="panel"><h2>我的旅行</h2><p>${state.token?'已通过手机号连接 Timelens 云端账户':'当前使用本地模式。使用小程序已绑定并验证的手机号登录，可同步原来的旅行数据。'}</p><div class="metrics" style="justify-content:flex-start;margin:30px 0"><div><b>${state.trips.length}</b><small>旅行计划</small></div><div><b>${state.records.length}</b><small>旅行记录</small></div><div><b>${state.markers.length}</b><small>足迹点位</small></div></div><button class="primary" id="tokenBtn">${state.token?'账户与同步设置':'手机号登录并同步'}</button></div>`;$('#tokenBtn').onclick=openLoginModal}
function navigate(page){state.page=page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const meta={explore:['路线广场','发现值得出发的路线灵感'],workspace:['计划工作台','规划、准备并记录一趟完整旅程'],footprints:['城市足迹','把走过的地方慢慢点亮'],profile:['我的旅行','管理你的计划与云端数据']}[page];$('#pageTitle').textContent=meta[0];$('#pageSub').textContent=meta[1];({explore:renderExplore,workspace:renderWorkspace,footprints:renderFootprints,profile:renderProfile}[page])();updateSide()}
function updateSide(){const t=active();$('#sideTrip').innerHTML=t?`<small>当前计划</small><b>${esc(t.title||t.destination+'之旅')}</b><p>${esc(t.startDate)} · ${esc(t.destination)}</p>`:'<small>当前计划</small><b>还没有旅行计划</b><p>创建后将在这里快速进入</p>'}
function showModal(html,onSubmit){const m=$('#modal'),f=$('#modalBody');f.innerHTML=html;f.querySelectorAll('button[value="cancel"]').forEach(btn=>{btn.type='button';btn.onclick=()=>m.close()});const error=document.createElement('div');error.className='modal-error';error.setAttribute('role','alert');error.hidden=true;const actions=f.querySelector('.modal-actions');actions?actions.before(error):f.prepend(error);f.onsubmit=async e=>{e.preventDefault();if(f.dataset.submitting)return;const submit=e.submitter||f.querySelector('button.primary'),label=submit?.textContent;error.hidden=true;delete error.dataset.kind;f.dataset.submitting='true';if(submit){submit.disabled=true;submit.textContent='处理中…'}try{await onSubmit(new FormData(f),m)}catch(err){error.textContent=err?.message||'操作失败，请稍后重试';error.dataset.kind=err?.status===409?'notice':'error';error.hidden=false;error.scrollIntoView({block:'nearest',behavior:'smooth'})}finally{delete f.dataset.submitting;if(submit&&m.open){submit.disabled=false;submit.textContent=label}}};m.showModal()}
function renderGuideDetail(g,records=[],status=''){const tags=g.tags||[g.days||'路线合集',g.budget||'轻松出发'];const stops=g.stops||g.route||g.itinerary||g.summary||g.notes||'这是一条值得慢慢体验的精选旅行路线。';const recordHtml=records.length?`<div style="margin-top:24px"><div class="section-head" style="margin:0 0 12px"><div><h2>逐日行程</h2><p>共 ${records.length} 条路线记录</p></div></div><div style="display:grid;gap:12px">${records.map((r,i)=>`<article class="record" style="display:grid;grid-template-columns:${r.imageUrl||r.image_url?'150px 1fr':'1fr'};gap:16px;align-items:start">${r.imageUrl||r.image_url?`<img src="${esc(r.imageUrl||r.image_url)}" alt="${esc(r.location||'路线记录')}" style="width:150px;height:110px;object-fit:cover;border-radius:10px">`:''}<div><time>DAY ${i+1} · ${esc(r.recordDate||r.record_date||r.date||'日期待定')}</time><h3>${esc(r.location||r.title||'当日行程')}</h3><p style="white-space:pre-wrap">${esc(r.essay||r.notes||r.content||'暂无记录说明')}</p>${r.mood?`<div class="tags"><span>${esc(r.mood)}</span></div>`:''}</div></article>`).join('')}</div></div>`:`<div class="empty" style="padding:28px;margin-top:20px">${esc(status||'这个合集暂时没有公开的逐日记录')}</div>`;const f=$('#modalBody');f.innerHTML=`<div class="cover" style="height:240px;border-radius:18px 18px 0 0;background-image:url('${esc(g.image||g.coverImage||g.cover_image||guides[0].image)}')"><span>${esc(g.city||g.destination||'精选路线')}</span></div><div style="padding:4px 2px"><span class="eyebrow">ROUTE GUIDE</span><h2 style="font-size:28px;margin:8px 0">${esc(g.title||g.name||'旅行路线')}</h2><p style="color:var(--muted);font-size:15px">${esc(g.summary||g.notes||'一条值得收藏的旅行路线')}</p><div class="tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="panel" style="margin-top:18px"><h3>路线详情</h3><p style="white-space:pre-wrap">${esc(typeof stops==='string'?stops:JSON.stringify(stops,null,2))}</p><div class="stats"><span>${esc(g.days||g.startDate||'随时出发')}</span><span>${esc(g.budget||'预算灵活')}　♡ ${g.likeCount||0}　⌁ ${g.viewCount||0}</span></div></div>${recordHtml}<div class="modal-actions"><button type="button" id="closeGuide">返回广场</button><button type="button" class="primary" id="useGuide">生成同款</button></div></div>`;$('#closeGuide').onclick=()=>$('#modal').close();$('#useGuide').onclick=()=>{$('#modal').close();openTripModal(g)}}
async function openGuideDetail(g){if(!g)return;showModal('',()=>{});renderGuideDetail(g,[],'正在加载逐日行程…');if(guides.some(x=>String(x.id)===String(g.id))){renderGuideDetail(g);return}try{const d=await api('/api/trips/public/'+encodeURIComponent(g.id));const records=arrayOf(d,['records','routeRecords','route_records']);const detail=d?.data?.trip||d?.trip||g;renderGuideDetail({...g,...detail},records)}catch(e){renderGuideDetail(g,[],'逐日行程加载失败：'+e.message)}}
function destinationNodeHtml(node){const children=Array.isArray(node.children)?node.children:[];return `<li class="destination-node"><div class="destination-node-row">${children.length?`<button type="button" class="destination-toggle" aria-label="展开 ${esc(node.name)}">›</button>`:'<span class="destination-toggle-spacer"></span>'}<button type="button" class="destination-choice" data-destination-code="${esc(node.code)}" data-destination-name="${esc(node.name)}" ${node.selectable?'':'disabled'}>${esc(node.name)}</button></div>${children.length?`<ul hidden>${children.map(destinationNodeHtml).join('')}</ul>`:''}</li>`}
function destinationResultsHtml(items){return items.length?items.map(item=>`<button type="button" class="destination-result" data-destination-code="${esc(item.code)}" data-destination-name="${esc(item.name)}"><b>${esc(item.name)}</b><small>${esc(item.fullName||'')}</small></button>`).join(''):'<p class="destination-empty">没有找到匹配目的地，可继续手动输入。</p>'}
function selectTripDestination(name,code){const input=$('#tripDestination'),codeInput=$('#tripDestinationCode');if(!input)return;input.value=name;if(codeInput)codeInput.value=code||'';input.dispatchEvent(new Event('input',{bubbles:true}));document.querySelectorAll('.destination-choice,.destination-result').forEach(x=>x.classList.toggle('selected',x.dataset.destinationCode===code))}
function bindDestinationPicker(onSelect=selectTripDestination){const tree=$('#destinationTree'),search=$('#destinationSearch'),results=$('#destinationResults');tree?.addEventListener('click',e=>{const toggle=e.target.closest('.destination-toggle');if(toggle){const childList=toggle.closest('li')?.querySelector(':scope > ul');if(childList){childList.hidden=!childList.hidden;toggle.classList.toggle('open',!childList.hidden)}return}const choice=e.target.closest('[data-destination-name]');if(choice&&!choice.disabled)onSelect(choice.dataset.destinationName,choice.dataset.destinationCode)});results?.addEventListener('click',e=>{const choice=e.target.closest('[data-destination-name]');if(choice)onSelect(choice.dataset.destinationName,choice.dataset.destinationCode)});let timer;search?.addEventListener('input',()=>{clearTimeout(timer);const q=search.value.trim();if(!q){results.innerHTML='';return}results.innerHTML='<p class="destination-empty">正在搜索…</p>';timer=setTimeout(async()=>{try{const data=await api(`/api/destinations/search?q=${encodeURIComponent(q)}&scene=trip&limit=20`);results.innerHTML=destinationResultsHtml(arrayOf(data))}catch(e){results.innerHTML='<p class="destination-empty">搜索暂不可用，可继续手动输入。</p>'}},250)})}
async function loadDestinationPicker(){const tree=$('#destinationTree');if(!tree)return;try{if(!destinationTreeCache){const data=await api('/api/destinations?scene=trip&format=tree');destinationTreeCache=arrayOf(data)}tree.innerHTML=destinationTreeCache.length?destinationTreeCache.map(destinationNodeHtml).join(''):'<li class="destination-empty">暂无目的地配置，可继续手动输入。</li>'}catch(e){tree.innerHTML='<li class="destination-empty">目的地目录暂不可用，可继续手动输入。</li>'}}
function openRouteDestinationFilter(){showModal(`<h2>按目的地筛选路线</h2><p>选择上级目的地时，会包含它下面所有地区的公开路线。</p><div class="destination-picker"><div class="destination-search-wrap"><input id="destinationSearch" type="search" placeholder="搜索城市、地区或国家"><span>⌕</span></div><div id="destinationResults" class="destination-results"></div><details class="destination-catalog" open><summary>按层级选择目的地</summary><ul id="destinationTree" class="destination-tree"><li class="destination-empty">正在加载目的地目录…</li></ul></details></div><div class="modal-actions"><button value="cancel">取消</button></div>`,()=>{});bindDestinationPicker((name,code)=>{state.destinationFilter={name,code};$('#modal').close();renderExplore()});loadDestinationPicker()}
function openTripModal(pref={}){showModal(`<h2>创建旅行计划</h2><div class="form-grid"><div class="field full"><label>目的地</label><input id="tripDestination" name="destination" required value="${esc(pref.city||'')}" placeholder="搜索或从下方目录选择，也可以手动输入"><input id="tripDestinationCode" type="hidden" name="destinationCode" value="${esc(pref.destinationCode||'')}"><div class="destination-picker"><div class="destination-search-wrap"><input id="destinationSearch" type="search" placeholder="搜索城市、地区或国家"><span>⌕</span></div><div id="destinationResults" class="destination-results"></div><details class="destination-catalog"><summary>按层级选择目的地</summary><ul id="destinationTree" class="destination-tree"><li class="destination-empty">正在加载目的地目录…</li></ul></details></div></div><div class="field"><label>出发日期</label><input type="date" name="startDate" required></div><div class="field"><label>结束日期</label><input type="date" name="endDate" required></div><div class="field"><label>预算</label><input name="budget" placeholder="例如 ¥5000"></div><div class="field"><label>同行方式</label><select name="companionLabel"><option>家人同行</option><option>朋友结伴</option><option>情侣出游</option><option>独自旅行</option></select></div><div class="field full"><label>偏好与备注</label><textarea name="notes">${esc(pref.summary||'')}</textarea></div></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">创建并开始规划</button></div>`,async(fd,m)=>{const o=Object.fromEntries(fd),trip={...o,id:'trip-'+Date.now(),title:o.destination+'之旅',rhythmLabel:'经典平衡',visibility:'private',createdAt:Date.now()};state.trips.unshift(trip);state.activeId=trip.id;addLocalDefaultChecklist(trip.id);persist();m.close();navigate('workspace');if(state.token)syncTrip(trip)});bindDestinationPicker();loadDestinationPicker()}
async function syncTrip(t,{publish=false}={}){
  if(!state.token){toast(publish?'请先登录，再公开路线':'登录后可将计划同步到云端');return null}
  try{
    if(String(t.id).startsWith('trip-')){
      const oldId=String(t.id),d=await api('/api/trips',{method:'POST',body:{...t,startDate:t.startDate,endDate:t.endDate,visibility:publish?'public':'private',isActive:true,clientCreatedAt:t.createdAt||Date.now()}}),saved=d.data||{};
      if(!saved.id)throw Error('云端没有返回旅行计划 ID');
      Object.assign(t,saved,{id:saved.id,startDate:saved.startDate||t.startDate,endDate:saved.endDate||t.endDate});
      state.checklist.forEach(item=>{if(String(item.tripId||'')===oldId)item.tripId=t.id});state.records.forEach(item=>{if(String(item.tripId||'')===oldId)item.tripId=t.id});state.activeId=t.id;
    }else if(publish){const d=await api(`/api/trips/${encodeURIComponent(t.id)}`,{method:'PUT',body:{visibility:'public',clientUpdatedAt:Date.now()}});Object.assign(t,d.data||{}, {visibility:'public'})}
    persist();updateSide();toast(publish?'已同步到路线广场':'旅行计划已同步到云端');return t;
  }catch(e){toast((publish?'路线发布失败：':'计划同步失败：')+e.message);return null}
}
function openCheckModal(){showModal(`<h2>添加清单项</h2><div class="field"><label>物品或事项</label><input name="name" required autofocus></div><div class="field"><label>备注</label><input name="desc"></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">添加</button></div>`,async(f,m)=>{const values=Object.fromEntries(f),t=active();if(state.token&&t&&!String(t.id).startsWith('trip-')){const d=await api(`/api/trips/${encodeURIComponent(t.id)}/checklist/items`,{method:'POST',body:{itemName:values.name,itemDesc:values.desc,categoryKey:'custom',categoryName:'自定义补充',source:'custom'}});state.checklist.push(normalizeChecklistItem(d.data||{}))}else state.checklist.push({id:Date.now(),tripId:t?.id,...values,categoryKey:'custom',categoryName:'自定义补充',done:false});persist();m.close();renderWorkspace()})}
function openRecordModal(){showModal(`<h2>新增单日记录</h2><div class="form-grid"><div class="field"><label>日期</label><input type="date" name="date" required></div><div class="field"><label>地点 / 路线标题</label><input name="location" required></div><div class="field full"><label>路线说明与提醒</label><textarea name="essay"></textarea></div></div><div class="modal-actions"><button value="cancel">取消</button><button class="primary">保存记录</button></div>`,(f,m)=>{state.records.unshift({id:'record-'+Date.now(),tripId:active().id,...Object.fromEntries(f),createdAt:Date.now()});persist();m.close();renderWorkspace()})}
function fillMarkerDestination(name,code){selectTripDestination(name,code);const coords=cityCoords[String(name).replace(/[市区县]$/,'')],latitude=document.querySelector('[name="latitude"]'),longitude=document.querySelector('[name="longitude"]');if(coords){latitude.value=coords[0];longitude.value=coords[1]}else{latitude.value='';longitude.value=''}}
function openMarkerModal(){showModal(`<h2>点亮一座城市</h2><div class="field"><label>城市或目的地</label><input id="tripDestination" name="city" required placeholder="搜索或从目录选择"><input id="tripDestinationCode" type="hidden" name="destinationCode"><div class="destination-picker"><div class="destination-search-wrap"><input id="destinationSearch" type="search" placeholder="搜索城市、地区或国家"><span>⌕</span></div><div id="destinationResults" class="destination-results"></div><details class="destination-catalog"><summary>按层级选择目的地</summary><ul id="destinationTree" class="destination-tree"><li class="destination-empty">正在加载目的地目录…</li></ul></details></div></div><div class="field"><label>地点备注</label><input name="name" placeholder="例如：西湖断桥"></div><div class="form-grid"><div class="field"><label>纬度（可选）</label><input name="latitude" type="number" step="any" placeholder="选择目的地后自动填写"></div><div class="field"><label>经度（可选）</label><input name="longitude" type="number" step="any" placeholder="选择目的地后自动填写"></div></div><p style="color:var(--muted);font-size:12px">选择目的地后会自动填写中心点坐标，也可以按具体地点手动调整。</p><div class="modal-actions"><button value="cancel">取消</button><button class="primary">点亮</button></div>`,async(f,m)=>{const data=Object.fromEntries(f),fallback=cityCoords[String(data.city).replace(/[市区县]$/,'')];if(!data.latitude&&fallback)data.latitude=fallback[0];if(!data.longitude&&fallback)data.longitude=fallback[1];let marker={id:'marker-'+Date.now(),...data,punchTime:Date.now()};const trip=active();if(state.token&&trip){const synced=String(trip.id).startsWith('trip-')?await syncTrip(trip):trip;if(synced){const d=await api('/api/markers',{method:'POST',body:{tripId:synced.id,name:data.city,address:data.name||'',destinationCode:data.destinationCode||null,latitude:data.latitude||null,longitude:data.longitude||null,punchTime:Date.now(),clientCreatedAt:Date.now()}});marker={...marker,...(d.data||{}),city:data.city}}}state.markers.unshift(marker);state.footprintSummary=null;persist();m.close();renderFootprints()});bindDestinationPicker(fillMarkerDestination);loadDestinationPicker()}
function openLoginModal(){
  let authMode='login';
  showModal(`<div class="mobile-login"><span class="eyebrow">ACCOUNT LOGIN</span><h2 id="authHeading">${state.token?'账户与云端同步':'手机号密码登录'}</h2><p id="authIntro">${state.token?'当前浏览器已连接云端账户。':'登录后即可取回原来的旅行计划、记录和城市足迹。'}</p>${state.token?'<div class="login-connected">● 云端账户已连接</div>':`<div class="auth-mode-switch" role="tablist" aria-label="登录或注册"><button type="button" class="active" data-auth-mode="login">登录</button><button type="button" data-auth-mode="register">注册新账户</button></div><div class="field"><label>手机号</label><input name="mobile" inputmode="numeric" autocomplete="username" maxlength="11" required placeholder="请输入 11 位手机号"></div><div class="field"><label>密码</label><input name="password" type="password" autocomplete="current-password" maxlength="72" required placeholder="请输入密码"></div><div id="registerFields" hidden><div class="field"><label>确认密码</label><input name="registerPasswordConfirm" type="password" autocomplete="new-password" maxlength="72" placeholder="再次输入密码"></div><p class="login-note">新用户可直接注册。密码需为 10–72 位，并同时包含字母和数字。</p></div><div id="loginOptions"><details class="activation-settings"><summary>原小程序用户首次在电脑端登录？</summary><div class="activation-guide"><b>如何获取激活码</b><ol><li>关注微信公众号「小梁游记」</li><li>将小程序已绑定的手机号提供给作者</li><li>作者核验后发送一次性激活码</li></ol><p>激活码仅可使用一次，生成后 30 分钟内有效，请收到后尽快完成设置。</p></div><div class="field"><label>一次性激活码</label><input name="activationCode" autocomplete="one-time-code" placeholder="请输入作者提供的激活码"></div><div class="field"><label>确认密码</label><input name="passwordConfirm" type="password" autocomplete="new-password" maxlength="72" placeholder="再次输入密码"></div><p class="login-note">激活后会自动关联原微信账户数据。</p></details><p class="login-note">已有账户直接登录；原小程序用户使用激活码关联历史数据。</p></div>`}</div><details class="token-settings"><summary>高级设置</summary><p>仅供调试或已有访问令牌的用户使用。</p><div class="field"><label>Access Token</label><textarea name="token">${esc(state.token)}</textarea></div></details><div class="modal-actions"><button type="button" id="loginClose">取消</button>${state.token?'<button type="button" id="logoutBtn">退出登录</button><button class="primary">更新令牌</button>':'<button class="primary" id="authSubmit">登录并同步</button>'}</div>`,async(f,m)=>{
    const manual=String(f.get('token')||'').trim();
    let token=manual;
    if(!token){
      const mobile=String(f.get('mobile')||'').trim(),password=String(f.get('password')||''),activationCode=String(f.get('activationCode')||'').trim();
      if(!/^1[3-9]\d{9}$/.test(mobile))throw new Error('请输入正确的 11 位手机号');
      let d;
      if(authMode==='register'){
        const confirm=String(f.get('registerPasswordConfirm')||'');
        if(password!==confirm)throw new Error('两次输入的密码不一致');
        d=await api('/api/auth/mobile/register',{method:'POST',body:{mobile,password}});
      }else if(activationCode){
        const confirm=String(f.get('passwordConfirm')||'');
        if(password!==confirm)throw new Error('两次输入的密码不一致');
        d=await api('/api/auth/mobile/activate',{method:'POST',body:{mobile,password,activationCode}});
      }else d=await api('/api/auth/mobile/password-login',{method:'POST',body:{mobile,password}});
      token=d?.data?.token||'';
    }
    if(!token)throw new Error(authMode==='register'?'注册失败，请稍后再试':'登录失败，请稍后再试');
    state.token=token;store.set('token',token);markerSyncAttempted=false;await syncAccountData();m.close();navigate('profile');refreshNotificationBadge();toast(authMode==='register'?'注册成功，欢迎使用时光透卡':'登录并同步成功');
  });
  const setAuthMode=mode=>{
    authMode=mode;
    document.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));
    const registering=mode==='register';
    $('#registerFields').hidden=!registering;
    $('#loginOptions').hidden=registering;
    $('#authHeading').textContent=registering?'创建时光透卡账户':'手机号密码登录';
    $('#authIntro').textContent=registering?'使用手机号和独立密码注册，创建你的旅行计划与城市足迹。':'登录后即可取回原来的旅行计划、记录和城市足迹。';
    $('#authSubmit').textContent=registering?'注册并登录':'登录并同步';
    document.querySelector('[name="password"]').autocomplete=registering?'new-password':'current-password';
  };
  document.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>setAuthMode(button.dataset.authMode));
  $('#loginClose').onclick=()=>$('#modal').close();
  $('#logoutBtn')?.addEventListener('click',()=>{state.token='';store.set('token','');markerSyncAttempted=false;$('#modal').close();refreshNotificationBadge();toast('已退出云端账户');navigate('profile')});
}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>navigate(x.dataset.page));$('#newTrip').onclick=()=>openTripModal();$('#loginBtn').onclick=()=>navigate('profile');$('#searchBtn').onclick=openSearchModal;$('#notificationBtn').onclick=openNotifications;const miniappModal=$('#miniappModal');$('#miniappBtn').onclick=()=>miniappModal.showModal();$('#miniappClose').onclick=()=>miniappModal.close();miniappModal.onclick=e=>{if(e.target===miniappModal)miniappModal.close()};content.addEventListener('click',e=>{const c=e.target.closest('[data-route]');if(c)location.href='/timelens-route?id='+encodeURIComponent(c.dataset.route)});navigate('explore');refreshNotificationBadge();if(new URLSearchParams(location.search).get('login')==='1'&&!state.token){openLoginModal();history.replaceState(null,'','/timelens')}
