const API_BASE='https://timelens.cc';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const builtins={hangzhou:{id:'hangzhou',destination:'杭州',title:'西湖城市漫游周末线',notes:'把湖滨散步、宋韵街区和咖啡慢游串成一条节奏舒服的两天一夜路线。',coverImage:'https://timelens.cc/images/official-changping.jpg',days:'2 天 1 夜',budget:'¥1200 - ¥1800',tags:['城市漫步','亲子友好','拍照出片']},xiamen:{id:'xiamen',destination:'厦门',title:'海风疗愈三日轻旅行',notes:'把鼓浪屿、海岸线和夜晚海风都装进一趟轻盈旅行。',coverImage:'https://timelens.cc/images/official-city-night.jpg',days:'3 天 2 夜',budget:'¥1800 - ¥2600',tags:['海边散心','文艺巡游','情侣友好']},dali:{id:'dali',destination:'大理',title:'苍洱之间的慢节奏假期',notes:'从古城到洱海，把风景、轻徒步与发呆时间都纳入路线安排。',coverImage:'https://timelens.cc/images/official-family-coast.jpg',days:'4 天 3 夜',budget:'¥2600 - ¥3600',tags:['自然风景','慢旅行','氛围感']}};
function toast(msg){const n=$('#notice');n.textContent=msg;n.hidden=false;setTimeout(()=>n.hidden=true,2600)}
function render(trip,records=[]){document.title=`${trip.title||'路线详情'} · 时光透卡`;const cover=trip.coverImage||trip.cover_image||'https://timelens.cc/images/official-city-night.jpg';const tags=trip.tags||['路线合集',trip.rhythmLabel||trip.rhythm_label||'自在出发'];$('#routeContent').innerHTML=`<section class="route-hero" style="--cover:url('${esc(cover)}')"><div><span class="eyebrow">SHAREABLE ROUTE GUIDE</span><h1>${esc(trip.title||'旅行路线')}</h1><p>${esc(trip.destination||'精选路线')} · ${esc(trip.startDate||trip.start_date||trip.days||'随时出发')}</p><div class="tags">${tags.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div></section><section class="route-summary"><h2>路线概览</h2><p>${esc(trip.notes||trip.summary||'一条值得收藏的旅行路线。')}</p><div class="stats"><span>${esc(trip.budget||'预算灵活')}</span><span>♡ ${trip.likeCount||trip.like_count||0}　⌁ ${trip.viewCount||trip.view_count||0}</span></div></section><div class="route-section-head"><h2>逐日行程</h2><p>${records.length?`共 ${records.length} 条路线记录`:'这个合集暂时没有公开的逐日记录'}</p></div><section class="route-timeline">${records.map((r,i)=>`<article class="day-record"><time>DAY ${i+1}<br>${esc(r.recordDate||r.record_date||r.date||'')}</time><div><h2>${esc(r.location||r.title||'当日行程')}</h2><p>${esc(r.essay||r.notes||r.content||'暂无记录说明')}</p>${r.imageUrl||r.image_url?`<img src="${esc(r.imageUrl||r.image_url)}" alt="${esc(r.location||'路线记录')}">`:''}</div></article>`).join('')}</section>`}
async function load(){const id=new URLSearchParams(location.search).get('id');if(!id){$('#routeContent').innerHTML='<div class="empty"><h2>缺少路线参数</h2><p>请从路线广场重新选择路线。</p></div>';return}if(builtins[id]){render(builtins[id]);return}try{const r=await fetch(`${API_BASE}/api/trips/public/${encodeURIComponent(id)}`);const d=await r.json();if(!r.ok||d.success===false)throw Error(d.message||d.error||`请求失败 (${r.status})`);const root=d.data||d.result||d;render(root.trip||root.routeCollection||root.route_collection||root,root.records||root.routeRecords||root.route_records||[])}catch(e){$('#routeContent').innerHTML=`<div class="empty"><h2>路线加载失败</h2><p>${esc(e.message)}</p><a class="primary" href="/timelens">返回路线广场</a></div>`}}
$('#shareRoute').onclick=async()=>{const data={title:document.title,text:'我发现了一条值得出发的旅行路线',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast('路线链接已复制')}}catch(e){if(e.name!=='AbortError')toast('分享失败，请复制浏览器地址')}};
load();
